tasks:
  - name: 'Update models'
    file_glob: './src/stripe/models/*cr'
    changes:
      -
        name: "card_present"
        pattern: 'ignore_serialize: card_present\.'
        new_value: 'ignore_serialize: card_present2.'
      -
        name: "card_present"
        pattern: 'property card_present :'
        new_value: 'property card_present2 :'
      -
        name: "card_present"
        pattern: '@card_present '
        new_value: '@card_present2 '
      -
        name: "card_present"
        pattern: '@card_present,'
        new_value: '@card_present2,'
      -
        name: "card_present_present"
        pattern: 'card_present_present'
        new_value: 'card_present2_present'
  - name: 'Update all'
    file_glob: './src/stripe/**/cr'
    changes:
      -
        name: 'Correct JSON::Any?'
        pattern: 'JSON::Any\?'
        new_value: 'JSON::Any'
      -
        name: 'Correct Stripe::String'
        pattern: 'Stripe::String'
        new_value: 'String'
      -
        name: 'Correct Int32'
        pattern: 'Int32'
        new_value: 'Int64'
  - name: 'Update api error'
    file_glob: './src/stripe/api_error.cr'
    changes:
      -
        name: 'Correct Int64'
        pattern: 'Int64'
        new_value: 'Int32'
