tasks:
  - name: 'Update models'
    file_glob: './src/stripe/models/*cr'
    changes:
      -
        name: "card_present"
        pattern: 'ignore_serialize: card_present\.'
        new_value: 'ignore_serialize: card_present2.'
      -
        name: "card_present"
        pattern: 'property card_present :'
        new_value: 'property card_present2 :'
      -
        name: "card_present"
        pattern: '@card_present '
        new_value: '@card_present2 '
      -
        name: "card_present"
        pattern: '@card_present,'
        new_value: '@card_present2,'
      -
        name: "card_present_present"
        pattern: 'card_present_present'
        new_value: 'card_present2_present'
  - name: 'Update all'
    file_glob: './src/stripe/**/*.cr'
    changes:
      -
        name: 'Correct JSON::Any?'
        pattern: 'JSON::Any\?'
        new_value: 'JSON::Any?'
      -
        name: 'Correct JSONAny'
        pattern: 'JSONAny'
        new_value: 'JSON::Any'
      -
        name: 'Correct Stripe::String'
        pattern: 'Stripe::String'
        new_value: 'String'
      -
        name: 'Correct Int32'
        pattern: ': Int32'
        new_value: ': Int64'
      -
        name: 'Correct ::::'
        pattern: '::::'
        new_value: '::'
      -
        name: "Remove empty if blocks"
        pattern: '^\s+if _[^\s]+ = [^\s]+$\n^\s+end$'
        new_value: ''
        multi_line: true
      -
        name: "Remove empty if blocks"
        pattern: '^\s+if [^\s]+$\n^\s+end$'
        new_value: ''
        multi_line: true
      -
        name: "Remove empty unless blocks"
        pattern: '(^\s+unless [^\s]+ = [^\s]+$\n^\s+end$|^\s+unless [^\s]+$\n^\s+end$)'
        new_value: ''
        multi_line: true
      # -
      #   name: "Replace 1?"
      #   pattern: '1\?'
      #   new_value: '?'
      # -
      #   name: "Replace 1)"
      #   pattern: '1\)'
      #   new_value: ')'
  - name: 'Update api error'
    file_glob: './src/stripe/api_error.cr'
    changes:
      -
        name: 'Correct Int64'
        pattern: 'Int64'
        new_value: 'Int32'
  - name: 'Update api error'
    file_glob: './src/stripe/api_client.cr'
    changes:
      -
        name: 'Correct Int64'
        pattern: 'Int64'
        new_value: 'Int32'
