require "./src/stripe.cr"
require "file_utils"

FileUtils.mkdir_p("local/gets")

Stripe.configure do |config|
  config.access_token = "sk_test_4eC39HqLyjWDarjtT1zdp7dc"
end

api = Stripe::DefaultApi.new
get_account = api.get_account(expand: nil)
File.write("local/gets/get_account.json", get_account.to_json)
# get_account_bank_accounts_id = api.get_account_bank_accounts_id(id: nil)
# File.write("local/gets/get_account_bank_accounts_id.json", get_account_bank_accounts_id.to_json)
get_account_capabilities = api.get_account_capabilities(expand: nil)
File.write("local/gets/get_account_capabilities.json", get_account_capabilities.to_json)
# get_account_capabilities_capability = api.get_account_capabilities_capability(capability: nil)
# File.write("local/gets/get_account_capabilities_capability.json", get_account_capabilities_capability.to_json)
# get_account_external_accounts = api.get_account_external_accounts(ending_before: nil, expand: nil, limit: nil, starting_after: nil)
# File.write("local/gets/get_account_external_accounts.json", get_account_external_accounts.to_json)
# get_account_external_accounts_id = api.get_account_external_accounts_id(id: nil)
# File.write("local/gets/get_account_external_accounts_id.json", get_account_external_accounts_id.to_json)
# get_account_people = api.get_account_people(ending_before: nil, expand: nil, limit: nil, relationship: nil, starting_after: nil)
# File.write("local/gets/get_account_people.json", get_account_people.to_json)
# get_account_people_person = api.get_account_people_person(person: nil)
# File.write("local/gets/get_account_people_person.json", get_account_people_person.to_json)
# get_account_persons = api.get_account_persons(ending_before: nil, expand: nil, limit: nil, relationship: nil, starting_after: nil)
# File.write("local/gets/get_account_persons.json", get_account_persons.to_json)
# get_account_persons_person = api.get_account_persons_person(person: nil)
# File.write("local/gets/get_account_persons_person.json", get_account_persons_person.to_json)
get_accounts = api.get_accounts(created: nil, ending_before: nil, expand: nil, limit: nil, starting_after: nil)
File.write("local/gets/get_accounts.json", get_accounts.to_json)
# get_accounts_account = api.get_accounts_account(account: nil)
# File.write("local/gets/get_accounts_account.json", get_accounts_account.to_json)
# get_accounts_account_bank_accounts_id = api.get_accounts_account_bank_accounts_id(account: nil)
# File.write("local/gets/get_accounts_account_bank_accounts_id.json", get_accounts_account_bank_accounts_id.to_json)
# get_accounts_account_capabilities = api.get_accounts_account_capabilities(account: nil)
# File.write("local/gets/get_accounts_account_capabilities.json", get_accounts_account_capabilities.to_json)
# get_accounts_account_capabilities_capability = api.get_accounts_account_capabilities_capability(account: nil)
# File.write("local/gets/get_accounts_account_capabilities_capability.json", get_accounts_account_capabilities_capability.to_json)
# get_accounts_account_external_accounts = api.get_accounts_account_external_accounts(account: nil, expand: nil, limit: nil, starting_after: nil)
# File.write("local/gets/get_accounts_account_external_accounts.json", get_accounts_account_external_accounts.to_json)
# get_accounts_account_external_accounts_id = api.get_accounts_account_external_accounts_id(account: nil)
# File.write("local/gets/get_accounts_account_external_accounts_id.json", get_accounts_account_external_accounts_id.to_json)
# get_accounts_account_people = api.get_accounts_account_people(account: nil, expand: nil, limit: nil, relationship: nil, starting_after: nil)
# File.write("local/gets/get_accounts_account_people.json", get_accounts_account_people.to_json)
# get_accounts_account_people_person = api.get_accounts_account_people_person(account: nil)
# File.write("local/gets/get_accounts_account_people_person.json", get_accounts_account_people_person.to_json)
# get_accounts_account_persons = api.get_accounts_account_persons(account: nil, expand: nil, limit: nil, relationship: nil, starting_after: nil)
# File.write("local/gets/get_accounts_account_persons.json", get_accounts_account_persons.to_json)
# get_accounts_account_persons_person = api.get_accounts_account_persons_person(account: nil)
# File.write("local/gets/get_accounts_account_persons_person.json", get_accounts_account_persons_person.to_json)
get_apple_pay_domains = api.get_apple_pay_domains(domain_name: nil, ending_before: nil, expand: nil, limit: nil, starting_after: nil)
File.write("local/gets/get_apple_pay_domains.json", get_apple_pay_domains.to_json)
# get_apple_pay_domains_domain = api.get_apple_pay_domains_domain(domain: nil)
# File.write("local/gets/get_apple_pay_domains_domain.json", get_apple_pay_domains_domain.to_json)
get_application_fees = api.get_application_fees(charge: nil, created: nil, ending_before: nil, expand: nil, limit: nil, starting_after: nil)
File.write("local/gets/get_application_fees.json", get_application_fees.to_json)
# get_application_fees_fee_refunds_id = api.get_application_fees_fee_refunds_id(fee: nil)
# File.write("local/gets/get_application_fees_fee_refunds_id.json", get_application_fees_fee_refunds_id.to_json)
# get_application_fees_id = api.get_application_fees_id(id: nil)
# File.write("local/gets/get_application_fees_id.json", get_application_fees_id.to_json)
# get_application_fees_id_refunds = api.get_application_fees_id_refunds(id: nil, expand: nil, limit: nil, starting_after: nil)
# File.write("local/gets/get_application_fees_id_refunds.json", get_application_fees_id_refunds.to_json)
# get_apps_secrets = api.get_apps_secrets(scope: nil, expand: nil, limit: nil, starting_after: nil)
# File.write("local/gets/get_apps_secrets.json", get_apps_secrets.to_json)
# get_apps_secrets_find = api.get_apps_secrets_find(name: nil)
# File.write("local/gets/get_apps_secrets_find.json", get_apps_secrets_find.to_json)
get_balance = api.get_balance(expand: nil)
File.write("local/gets/get_balance.json", get_balance.to_json)
get_balance_history = api.get_balance_history(created: nil, currency: nil, ending_before: nil, expand: nil, limit: nil, payout: nil, source: nil, starting_after: nil, _type: nil)
File.write("local/gets/get_balance_history.json", get_balance_history.to_json)
# get_balance_history_id = api.get_balance_history_id(id: nil)
# File.write("local/gets/get_balance_history_id.json", get_balance_history_id.to_json)
get_balance_transactions = api.get_balance_transactions(created: nil, currency: nil, ending_before: nil, expand: nil, limit: nil, payout: nil, source: nil, starting_after: nil, _type: nil)
File.write("local/gets/get_balance_transactions.json", get_balance_transactions.to_json)
# get_balance_transactions_id = api.get_balance_transactions_id(id: nil)
# File.write("local/gets/get_balance_transactions_id.json", get_balance_transactions_id.to_json)
get_billing_portal_configurations = api.get_billing_portal_configurations(active: nil, ending_before: nil, expand: nil, is_default: nil, limit: nil, starting_after: nil)
File.write("local/gets/get_billing_portal_configurations.json", get_billing_portal_configurations.to_json)
# get_billing_portal_configurations_configuration = api.get_billing_portal_configurations_configuration(configuration: nil)
# File.write("local/gets/get_billing_portal_configurations_configuration.json", get_billing_portal_configurations_configuration.to_json)
get_bitcoin_receivers = api.get_bitcoin_receivers(active: nil, ending_before: nil, expand: nil, filled: nil, limit: nil, starting_after: nil, uncaptured_funds: nil)
File.write("local/gets/get_bitcoin_receivers.json", get_bitcoin_receivers.to_json)
# get_bitcoin_receivers_id = api.get_bitcoin_receivers_id(id: nil)
# File.write("local/gets/get_bitcoin_receivers_id.json", get_bitcoin_receivers_id.to_json)
# get_bitcoin_receivers_receiver_transactions = api.get_bitcoin_receivers_receiver_transactions(receiver: nil, ending_before: nil, expand: nil, limit: nil, starting_after: nil)
# File.write("local/gets/get_bitcoin_receivers_receiver_transactions.json", get_bitcoin_receivers_receiver_transactions.to_json)
get_bitcoin_transactions = api.get_bitcoin_transactions(customer: nil, ending_before: nil, expand: nil, limit: nil, receiver: nil, starting_after: nil)
File.write("local/gets/get_bitcoin_transactions.json", get_bitcoin_transactions.to_json)
get_charges = api.get_charges(created: nil, customer: nil, ending_before: nil, expand: nil, limit: nil, payment_intent: nil, starting_after: nil, transfer_group: nil)
File.write("local/gets/get_charges.json", get_charges.to_json)
# get_charges_charge = api.get_charges_charge(charge: nil)
# File.write("local/gets/get_charges_charge.json", get_charges_charge.to_json)
# get_charges_charge_dispute = api.get_charges_charge_dispute(charge: nil)
# File.write("local/gets/get_charges_charge_dispute.json", get_charges_charge_dispute.to_json)
# get_charges_charge_refunds = api.get_charges_charge_refunds(charge: nil, expand: nil, limit: nil, starting_after: nil)
# File.write("local/gets/get_charges_charge_refunds.json", get_charges_charge_refunds.to_json)
# get_charges_charge_refunds_refund = api.get_charges_charge_refunds_refund(charge: nil)
# File.write("local/gets/get_charges_charge_refunds_refund.json", get_charges_charge_refunds_refund.to_json)
# get_charges_search = api.get_charges_search(query: nil, limit: nil, page: nil)
# File.write("local/gets/get_charges_search.json", get_charges_search.to_json)
get_checkout_sessions = api.get_checkout_sessions(ending_before: nil, expand: nil, limit: nil, payment_intent: nil, starting_after: nil, subscription: nil)
File.write("local/gets/get_checkout_sessions.json", get_checkout_sessions.to_json)
# get_checkout_sessions_session = api.get_checkout_sessions_session(session: nil)
# File.write("local/gets/get_checkout_sessions_session.json", get_checkout_sessions_session.to_json)
# get_checkout_sessions_session_line_items = api.get_checkout_sessions_session_line_items(session: nil, expand: nil, limit: nil, starting_after: nil)
# File.write("local/gets/get_checkout_sessions_session_line_items.json", get_checkout_sessions_session_line_items.to_json)
get_country_specs = api.get_country_specs(ending_before: nil, expand: nil, limit: nil, starting_after: nil)
File.write("local/gets/get_country_specs.json", get_country_specs.to_json)
# get_country_specs_country = api.get_country_specs_country(country: nil)
# File.write("local/gets/get_country_specs_country.json", get_country_specs_country.to_json)
get_coupons = api.get_coupons(created: nil, ending_before: nil, expand: nil, limit: nil, starting_after: nil)
File.write("local/gets/get_coupons.json", get_coupons.to_json)
# get_coupons_coupon = api.get_coupons_coupon(coupon: nil)
# File.write("local/gets/get_coupons_coupon.json", get_coupons_coupon.to_json)
get_credit_notes = api.get_credit_notes(customer: nil, ending_before: nil, expand: nil, invoice: nil, limit: nil, starting_after: nil)
File.write("local/gets/get_credit_notes.json", get_credit_notes.to_json)
# get_credit_notes_credit_note_lines = api.get_credit_notes_credit_note_lines(credit_note: nil, expand: nil, limit: nil, starting_after: nil)
# File.write("local/gets/get_credit_notes_credit_note_lines.json", get_credit_notes_credit_note_lines.to_json)
# get_credit_notes_id = api.get_credit_notes_id(id: nil)
# File.write("local/gets/get_credit_notes_id.json", get_credit_notes_id.to_json)
# get_credit_notes_preview = api.get_credit_notes_preview(invoice: nil, credit_amount: nil, expand: nil, lines: nil, memo: nil, metadata: nil, out_of_band_amount: nil, reason: nil, refund: nil, refund_amount: nil)
# File.write("local/gets/get_credit_notes_preview.json", get_credit_notes_preview.to_json)
# get_credit_notes_preview_lines = api.get_credit_notes_preview_lines(invoice: nil, credit_amount: nil, ending_before: nil, expand: nil, limit: nil, lines: nil, memo: nil, metadata: nil, out_of_band_amount: nil, reason: nil, refund: nil, refund_amount: nil, starting_after: nil)
# File.write("local/gets/get_credit_notes_preview_lines.json", get_credit_notes_preview_lines.to_json)
get_customers = api.get_customers(created: nil, email: nil, ending_before: nil, expand: nil, limit: nil, starting_after: nil, test_clock: nil)
File.write("local/gets/get_customers.json", get_customers.to_json)
# get_customers_customer = api.get_customers_customer(customer: nil)
# File.write("local/gets/get_customers_customer.json", get_customers_customer.to_json)
# get_customers_customer_balance_transactions = api.get_customers_customer_balance_transactions(customer: nil, expand: nil, limit: nil, starting_after: nil)
# File.write("local/gets/get_customers_customer_balance_transactions.json", get_customers_customer_balance_transactions.to_json)
# get_customers_customer_balance_transactions_transaction = api.get_customers_customer_balance_transactions_transaction(customer: nil)
# File.write("local/gets/get_customers_customer_balance_transactions_transaction.json", get_customers_customer_balance_transactions_transaction.to_json)
# get_customers_customer_bank_accounts = api.get_customers_customer_bank_accounts(customer: nil, expand: nil, limit: nil, starting_after: nil)
# File.write("local/gets/get_customers_customer_bank_accounts.json", get_customers_customer_bank_accounts.to_json)
# get_customers_customer_bank_accounts_id = api.get_customers_customer_bank_accounts_id(customer: nil)
# File.write("local/gets/get_customers_customer_bank_accounts_id.json", get_customers_customer_bank_accounts_id.to_json)
# get_customers_customer_cards = api.get_customers_customer_cards(customer: nil, expand: nil, limit: nil, starting_after: nil)
# File.write("local/gets/get_customers_customer_cards.json", get_customers_customer_cards.to_json)
# get_customers_customer_cards_id = api.get_customers_customer_cards_id(customer: nil)
# File.write("local/gets/get_customers_customer_cards_id.json", get_customers_customer_cards_id.to_json)
# get_customers_customer_cash_balance = api.get_customers_customer_cash_balance(customer: nil)
# File.write("local/gets/get_customers_customer_cash_balance.json", get_customers_customer_cash_balance.to_json)
# get_customers_customer_discount = api.get_customers_customer_discount(customer: nil)
# File.write("local/gets/get_customers_customer_discount.json", get_customers_customer_discount.to_json)
# get_customers_customer_payment_methods = api.get_customers_customer_payment_methods(customer: nil, expand: nil, limit: nil, starting_after: nil)
# File.write("local/gets/get_customers_customer_payment_methods.json", get_customers_customer_payment_methods.to_json)
# get_customers_customer_payment_methods_payment_method = api.get_customers_customer_payment_methods_payment_method(customer: nil)
# File.write("local/gets/get_customers_customer_payment_methods_payment_method.json", get_customers_customer_payment_methods_payment_method.to_json)
# get_customers_customer_sources = api.get_customers_customer_sources(customer: nil, expand: nil, limit: nil, object: nil, starting_after: nil)
# File.write("local/gets/get_customers_customer_sources.json", get_customers_customer_sources.to_json)
# get_customers_customer_sources_id = api.get_customers_customer_sources_id(customer: nil)
# File.write("local/gets/get_customers_customer_sources_id.json", get_customers_customer_sources_id.to_json)
# get_customers_customer_subscriptions = api.get_customers_customer_subscriptions(customer: nil, expand: nil, limit: nil, starting_after: nil)
# File.write("local/gets/get_customers_customer_subscriptions.json", get_customers_customer_subscriptions.to_json)
# get_customers_customer_subscriptions_subscription_exposed_id = api.get_customers_customer_subscriptions_subscription_exposed_id(customer: nil)
# File.write("local/gets/get_customers_customer_subscriptions_subscription_exposed_id.json", get_customers_customer_subscriptions_subscription_exposed_id.to_json)
# get_customers_customer_subscriptions_subscription_exposed_id_discount = api.get_customers_customer_subscriptions_subscription_exposed_id_discount(customer: nil)
# File.write("local/gets/get_customers_customer_subscriptions_subscription_exposed_id_discount.json", get_customers_customer_subscriptions_subscription_exposed_id_discount.to_json)
# get_customers_customer_tax_ids = api.get_customers_customer_tax_ids(customer: nil, expand: nil, limit: nil, starting_after: nil)
# File.write("local/gets/get_customers_customer_tax_ids.json", get_customers_customer_tax_ids.to_json)
# get_customers_customer_tax_ids_id = api.get_customers_customer_tax_ids_id(customer: nil)
# File.write("local/gets/get_customers_customer_tax_ids_id.json", get_customers_customer_tax_ids_id.to_json)
# get_customers_search = api.get_customers_search(query: nil, limit: nil, page: nil)
# File.write("local/gets/get_customers_search.json", get_customers_search.to_json)
get_disputes = api.get_disputes(charge: nil, created: nil, ending_before: nil, expand: nil, limit: nil, payment_intent: nil, starting_after: nil)
File.write("local/gets/get_disputes.json", get_disputes.to_json)
# get_disputes_dispute = api.get_disputes_dispute(dispute: nil)
# File.write("local/gets/get_disputes_dispute.json", get_disputes_dispute.to_json)
get_events = api.get_events(created: nil, delivery_success: nil, ending_before: nil, expand: nil, limit: nil, starting_after: nil, _type: nil, types: nil)
File.write("local/gets/get_events.json", get_events.to_json)
# get_events_id = api.get_events_id(id: nil)
# File.write("local/gets/get_events_id.json", get_events_id.to_json)
# get_exchange_rates = api.get_exchange_rates(ending_before: nil, expand: nil, limit: nil, starting_after: nil)
# File.write("local/gets/get_exchange_rates.json", get_exchange_rates.to_json)
# get_exchange_rates_rate_id = api.get_exchange_rates_rate_id(rate_id: nil)
# File.write("local/gets/get_exchange_rates_rate_id.json", get_exchange_rates_rate_id.to_json)
get_file_links = api.get_file_links(created: nil, ending_before: nil, expand: nil, expired: nil, file: nil, limit: nil, starting_after: nil)
File.write("local/gets/get_file_links.json", get_file_links.to_json)
# get_file_links_link = api.get_file_links_link(link: nil)
# File.write("local/gets/get_file_links_link.json", get_file_links_link.to_json)
# get_files = api.get_files(created: nil, ending_before: nil, expand: nil, limit: nil, purpose: nil, starting_after: nil)
# File.write("local/gets/get_files.json", get_files.to_json)
# get_files_file = api.get_files_file(file: nil)
# File.write("local/gets/get_files_file.json", get_files_file.to_json)
get_financial_connections_accounts = api.get_financial_connections_accounts(account_holder: nil, ending_before: nil, expand: nil, limit: nil, session: nil, starting_after: nil)
File.write("local/gets/get_financial_connections_accounts.json", get_financial_connections_accounts.to_json)
# get_financial_connections_accounts_account = api.get_financial_connections_accounts_account(account: nil)
# File.write("local/gets/get_financial_connections_accounts_account.json", get_financial_connections_accounts_account.to_json)
# get_financial_connections_accounts_account_owners = api.get_financial_connections_accounts_account_owners(account: nil, expand: nil, limit: nil, starting_after: nil)
# File.write("local/gets/get_financial_connections_accounts_account_owners.json", get_financial_connections_accounts_account_owners.to_json)
# get_financial_connections_sessions_session = api.get_financial_connections_sessions_session(session: nil)
# File.write("local/gets/get_financial_connections_sessions_session.json", get_financial_connections_sessions_session.to_json)
get_identity_verification_reports = api.get_identity_verification_reports(created: nil, ending_before: nil, expand: nil, limit: nil, starting_after: nil, _type: nil, verification_session: nil)
File.write("local/gets/get_identity_verification_reports.json", get_identity_verification_reports.to_json)
# get_identity_verification_reports_report = api.get_identity_verification_reports_report(report: nil)
# File.write("local/gets/get_identity_verification_reports_report.json", get_identity_verification_reports_report.to_json)
get_identity_verification_sessions = api.get_identity_verification_sessions(created: nil, ending_before: nil, expand: nil, limit: nil, starting_after: nil, status: nil)
File.write("local/gets/get_identity_verification_sessions.json", get_identity_verification_sessions.to_json)
# get_identity_verification_sessions_session = api.get_identity_verification_sessions_session(session: nil)
# File.write("local/gets/get_identity_verification_sessions_session.json", get_identity_verification_sessions_session.to_json)
get_invoiceitems = api.get_invoiceitems(created: nil, customer: nil, ending_before: nil, expand: nil, invoice: nil, limit: nil, pending: nil, starting_after: nil)
File.write("local/gets/get_invoiceitems.json", get_invoiceitems.to_json)
# get_invoiceitems_invoiceitem = api.get_invoiceitems_invoiceitem(invoiceitem: nil)
# File.write("local/gets/get_invoiceitems_invoiceitem.json", get_invoiceitems_invoiceitem.to_json)
get_invoices = api.get_invoices(collection_method: nil, created: nil, customer: nil, due_date: nil, ending_before: nil, expand: nil, limit: nil, starting_after: nil, status: nil, subscription: nil)
File.write("local/gets/get_invoices.json", get_invoices.to_json)
# get_invoices_invoice = api.get_invoices_invoice(invoice: nil)
# File.write("local/gets/get_invoices_invoice.json", get_invoices_invoice.to_json)
# get_invoices_invoice_lines = api.get_invoices_invoice_lines(invoice: nil, expand: nil, limit: nil, starting_after: nil)
# File.write("local/gets/get_invoices_invoice_lines.json", get_invoices_invoice_lines.to_json)
# get_invoices_search = api.get_invoices_search(query: nil, limit: nil, page: nil)
# File.write("local/gets/get_invoices_search.json", get_invoices_search.to_json)
# get_invoices_upcoming = api.get_invoices_upcoming(automatic_tax: nil, coupon: nil, customer: "cus_4QE41GDczMg5d5", customer_details: nil, discounts: nil, expand: nil, invoice_items: nil, schedule: nil, subscription: nil, subscription_billing_cycle_anchor: nil, subscription_cancel_at: nil, subscription_cancel_at_period_end: nil, subscription_cancel_now: nil, subscription_default_tax_rates: nil, subscription_items: nil, subscription_proration_behavior: nil, subscription_proration_date: nil, subscription_start_date: nil, subscription_trial_end: nil, subscription_trial_from_plan: nil)
# File.write("local/gets/get_invoices_upcoming.json", get_invoices_upcoming.to_json)
# get_invoices_upcoming_lines = api.get_invoices_upcoming_lines(automatic_tax: nil, coupon: nil, customer: "cus_4QE41GDczMg5d5", customer_details: nil, discounts: nil, ending_before: nil, expand: nil, invoice_items: nil, limit: nil, schedule: nil, starting_after: nil, subscription: nil, subscription_billing_cycle_anchor: nil, subscription_cancel_at: nil, subscription_cancel_at_period_end: nil, subscription_cancel_now: nil, subscription_default_tax_rates: nil, subscription_items: nil, subscription_proration_behavior: nil, subscription_proration_date: nil, subscription_start_date: nil, subscription_trial_end: nil, subscription_trial_from_plan: nil)
# File.write("local/gets/get_invoices_upcoming_lines.json", get_invoices_upcoming_lines.to_json)
# get_issuer_fraud_records = api.get_issuer_fraud_records(charge: nil, ending_before: nil, expand: nil, limit: nil, starting_after: nil)
# File.write("local/gets/get_issuer_fraud_records.json", get_issuer_fraud_records.to_json)
# get_issuer_fraud_records_issuer_fraud_record = api.get_issuer_fraud_records_issuer_fraud_record(issuer_fraud_record: nil)
# File.write("local/gets/get_issuer_fraud_records_issuer_fraud_record.json", get_issuer_fraud_records_issuer_fraud_record.to_json)
# get_issuing_authorizations = api.get_issuing_authorizations(card: nil, cardholder: nil, created: nil, ending_before: nil, expand: nil, limit: nil, starting_after: nil, status: nil)
# File.write("local/gets/get_issuing_authorizations.json", get_issuing_authorizations.to_json)
# get_issuing_authorizations_authorization = api.get_issuing_authorizations_authorization(authorization: nil)
# File.write("local/gets/get_issuing_authorizations_authorization.json", get_issuing_authorizations_authorization.to_json)
# get_issuing_cardholders = api.get_issuing_cardholders(created: nil, email: nil, ending_before: nil, expand: nil, limit: nil, phone_number: nil, starting_after: nil, status: nil, _type: nil)
# File.write("local/gets/get_issuing_cardholders.json", get_issuing_cardholders.to_json)
# get_issuing_cardholders_cardholder = api.get_issuing_cardholders_cardholder(cardholder: nil)
# File.write("local/gets/get_issuing_cardholders_cardholder.json", get_issuing_cardholders_cardholder.to_json)
# get_issuing_cards = api.get_issuing_cards(cardholder: nil, created: nil, ending_before: nil, exp_month: nil, exp_year: nil, expand: nil, last4: nil, limit: nil, starting_after: nil, status: nil, _type: nil)
# File.write("local/gets/get_issuing_cards.json", get_issuing_cards.to_json)
# get_issuing_cards_card = api.get_issuing_cards_card(card: nil)
# File.write("local/gets/get_issuing_cards_card.json", get_issuing_cards_card.to_json)
# get_issuing_disputes = api.get_issuing_disputes(created: nil, ending_before: nil, expand: nil, limit: nil, starting_after: nil, status: nil, transaction: nil)
# File.write("local/gets/get_issuing_disputes.json", get_issuing_disputes.to_json)
# get_issuing_disputes_dispute = api.get_issuing_disputes_dispute(dispute: nil)
# File.write("local/gets/get_issuing_disputes_dispute.json", get_issuing_disputes_dispute.to_json)
# get_issuing_settlements = api.get_issuing_settlements(created: nil, ending_before: nil, expand: nil, limit: nil, starting_after: nil)
# File.write("local/gets/get_issuing_settlements.json", get_issuing_settlements.to_json)
# get_issuing_settlements_settlement = api.get_issuing_settlements_settlement(settlement: nil)
# File.write("local/gets/get_issuing_settlements_settlement.json", get_issuing_settlements_settlement.to_json)
# get_issuing_transactions = api.get_issuing_transactions(card: nil, cardholder: nil, created: nil, ending_before: nil, expand: nil, limit: nil, starting_after: nil, _type: nil)
# File.write("local/gets/get_issuing_transactions.json", get_issuing_transactions.to_json)
# get_issuing_transactions_transaction = api.get_issuing_transactions_transaction(transaction: nil)
# File.write("local/gets/get_issuing_transactions_transaction.json", get_issuing_transactions_transaction.to_json)
# get_link_account_sessions_session = api.get_link_account_sessions_session(session: nil)
# File.write("local/gets/get_link_account_sessions_session.json", get_link_account_sessions_session.to_json)
get_linked_accounts = api.get_linked_accounts(account_holder: nil, ending_before: nil, expand: nil, limit: nil, session: nil, starting_after: nil)
File.write("local/gets/get_linked_accounts.json", get_linked_accounts.to_json)
# get_linked_accounts_account = api.get_linked_accounts_account(account: nil)
# File.write("local/gets/get_linked_accounts_account.json", get_linked_accounts_account.to_json)
# get_linked_accounts_account_owners = api.get_linked_accounts_account_owners(account: nil, expand: nil, limit: nil, starting_after: nil)
# File.write("local/gets/get_linked_accounts_account_owners.json", get_linked_accounts_account_owners.to_json)
# get_mandates_mandate = api.get_mandates_mandate(mandate: nil)
# File.write("local/gets/get_mandates_mandate.json", get_mandates_mandate.to_json)
get_orders = api.get_orders(customer: nil, ending_before: nil, expand: nil, limit: nil, starting_after: nil)
File.write("local/gets/get_orders.json", get_orders.to_json)
# get_orders_id = api.get_orders_id(id: nil)
# File.write("local/gets/get_orders_id.json", get_orders_id.to_json)
# get_orders_id_line_items = api.get_orders_id_line_items(id: nil, expand: nil, limit: nil, starting_after: nil)
# File.write("local/gets/get_orders_id_line_items.json", get_orders_id_line_items.to_json)
get_payment_intents = api.get_payment_intents(created: nil, customer: nil, ending_before: nil, expand: nil, limit: nil, starting_after: nil)
File.write("local/gets/get_payment_intents.json", get_payment_intents.to_json)
# get_payment_intents_intent = api.get_payment_intents_intent(intent: nil, expand: nil)
# File.write("local/gets/get_payment_intents_intent.json", get_payment_intents_intent.to_json)
# get_payment_intents_search = api.get_payment_intents_search(query: nil, limit: nil, page: nil)
# File.write("local/gets/get_payment_intents_search.json", get_payment_intents_search.to_json)
get_payment_links = api.get_payment_links(active: nil, ending_before: nil, expand: nil, limit: nil, starting_after: nil)
File.write("local/gets/get_payment_links.json", get_payment_links.to_json)
# get_payment_links_payment_link = api.get_payment_links_payment_link(payment_link: nil)
# File.write("local/gets/get_payment_links_payment_link.json", get_payment_links_payment_link.to_json)
# get_payment_links_payment_link_line_items = api.get_payment_links_payment_link_line_items(payment_link: nil, expand: nil, limit: nil, starting_after: nil)
# File.write("local/gets/get_payment_links_payment_link_line_items.json", get_payment_links_payment_link_line_items.to_json)
# get_payment_methods = api.get_payment_methods(_type: nil, ending_before: nil, expand: nil, limit: nil, starting_after: nil)
# File.write("local/gets/get_payment_methods.json", get_payment_methods.to_json)
# get_payment_methods_payment_method = api.get_payment_methods_payment_method(payment_method: nil)
# File.write("local/gets/get_payment_methods_payment_method.json", get_payment_methods_payment_method.to_json)
get_payouts = api.get_payouts(arrival_date: nil, created: nil, destination: nil, ending_before: nil, expand: nil, limit: nil, starting_after: nil, status: nil)
File.write("local/gets/get_payouts.json", get_payouts.to_json)
# get_payouts_payout = api.get_payouts_payout(payout: nil)
# File.write("local/gets/get_payouts_payout.json", get_payouts_payout.to_json)
get_plans = api.get_plans(active: nil, created: nil, ending_before: nil, expand: nil, limit: nil, product: nil, starting_after: nil)
File.write("local/gets/get_plans.json", get_plans.to_json)
# get_plans_plan = api.get_plans_plan(plan: nil)
# File.write("local/gets/get_plans_plan.json", get_plans_plan.to_json)
get_prices = api.get_prices(active: nil, created: nil, currency: nil, ending_before: nil, expand: nil, limit: nil, lookup_keys: nil, product: nil, recurring: nil, starting_after: nil, _type: nil)
File.write("local/gets/get_prices.json", get_prices.to_json)
# get_prices_price = api.get_prices_price(price: nil)
# File.write("local/gets/get_prices_price.json", get_prices_price.to_json)
# get_prices_search = api.get_prices_search(query: nil, limit: nil, page: nil)
# File.write("local/gets/get_prices_search.json", get_prices_search.to_json)
get_products = api.get_products(active: nil, created: nil, ending_before: nil, expand: nil, ids: nil, limit: nil, shippable: nil, starting_after: nil, url: nil)
File.write("local/gets/get_products.json", get_products.to_json)
# get_products_id = api.get_products_id(id: nil)
# File.write("local/gets/get_products_id.json", get_products_id.to_json)
# get_products_search = api.get_products_search(query: nil, limit: nil, page: nil)
# File.write("local/gets/get_products_search.json", get_products_search.to_json)
get_promotion_codes = api.get_promotion_codes(active: nil, code: nil, coupon: nil, created: nil, customer: nil, ending_before: nil, expand: nil, limit: nil, starting_after: nil)
File.write("local/gets/get_promotion_codes.json", get_promotion_codes.to_json)
# get_promotion_codes_promotion_code = api.get_promotion_codes_promotion_code(promotion_code: nil)
# File.write("local/gets/get_promotion_codes_promotion_code.json", get_promotion_codes_promotion_code.to_json)
get_quotes = api.get_quotes(customer: nil, ending_before: nil, expand: nil, limit: nil, starting_after: nil, status: nil, test_clock: nil)
File.write("local/gets/get_quotes.json", get_quotes.to_json)
# get_quotes_quote = api.get_quotes_quote(quote: nil)
# File.write("local/gets/get_quotes_quote.json", get_quotes_quote.to_json)
# get_quotes_quote_computed_upfront_line_items = api.get_quotes_quote_computed_upfront_line_items(quote: nil, expand: nil, limit: nil, starting_after: nil)
# File.write("local/gets/get_quotes_quote_computed_upfront_line_items.json", get_quotes_quote_computed_upfront_line_items.to_json)
# get_quotes_quote_line_items = api.get_quotes_quote_line_items(quote: nil, expand: nil, limit: nil, starting_after: nil)
# File.write("local/gets/get_quotes_quote_line_items.json", get_quotes_quote_line_items.to_json)
# get_quotes_quote_pdf = api.get_quotes_quote_pdf(quote: nil)
# File.write("local/gets/get_quotes_quote_pdf.json", get_quotes_quote_pdf.to_json)
get_radar_early_fraud_warnings = api.get_radar_early_fraud_warnings(charge: nil, ending_before: nil, expand: nil, limit: nil, payment_intent: nil, starting_after: nil)
File.write("local/gets/get_radar_early_fraud_warnings.json", get_radar_early_fraud_warnings.to_json)
# get_radar_early_fraud_warnings_early_fraud_warning = api.get_radar_early_fraud_warnings_early_fraud_warning(early_fraud_warning: nil)
# File.write("local/gets/get_radar_early_fraud_warnings_early_fraud_warning.json", get_radar_early_fraud_warnings_early_fraud_warning.to_json)
# get_radar_value_list_items = api.get_radar_value_list_items(value_list: nil, ending_before: nil, expand: nil, limit: nil, starting_after: nil, value: nil)
# File.write("local/gets/get_radar_value_list_items.json", get_radar_value_list_items.to_json)
# get_radar_value_list_items_item = api.get_radar_value_list_items_item(item: nil)
# File.write("local/gets/get_radar_value_list_items_item.json", get_radar_value_list_items_item.to_json)
get_radar_value_lists = api.get_radar_value_lists(_alias: nil, contains: nil, created: nil, ending_before: nil, expand: nil, limit: nil, starting_after: nil)
File.write("local/gets/get_radar_value_lists.json", get_radar_value_lists.to_json)
# get_radar_value_lists_value_list = api.get_radar_value_lists_value_list(value_list: nil)
# File.write("local/gets/get_radar_value_lists_value_list.json", get_radar_value_lists_value_list.to_json)
get_recipients = api.get_recipients(created: nil, ending_before: nil, expand: nil, limit: nil, starting_after: nil, _type: nil, verified: nil)
File.write("local/gets/get_recipients.json", get_recipients.to_json)
# get_recipients_id = api.get_recipients_id(id: nil)
# File.write("local/gets/get_recipients_id.json", get_recipients_id.to_json)
get_refunds = api.get_refunds(charge: nil, created: nil, ending_before: nil, expand: nil, limit: nil, payment_intent: nil, starting_after: nil)
File.write("local/gets/get_refunds.json", get_refunds.to_json)
# get_refunds_refund = api.get_refunds_refund(refund: nil)
# File.write("local/gets/get_refunds_refund.json", get_refunds_refund.to_json)
get_reporting_report_runs = api.get_reporting_report_runs(created: nil, ending_before: nil, expand: nil, limit: nil, starting_after: nil)
File.write("local/gets/get_reporting_report_runs.json", get_reporting_report_runs.to_json)
# get_reporting_report_runs_report_run = api.get_reporting_report_runs_report_run(report_run: nil)
# File.write("local/gets/get_reporting_report_runs_report_run.json", get_reporting_report_runs_report_run.to_json)
get_reporting_report_types = api.get_reporting_report_types(expand: nil)
File.write("local/gets/get_reporting_report_types.json", get_reporting_report_types.to_json)
# get_reporting_report_types_report_type = api.get_reporting_report_types_report_type(report_type: nil)
# File.write("local/gets/get_reporting_report_types_report_type.json", get_reporting_report_types_report_type.to_json)
get_reviews = api.get_reviews(created: nil, ending_before: nil, expand: nil, limit: nil, starting_after: nil)
File.write("local/gets/get_reviews.json", get_reviews.to_json)
# get_reviews_review = api.get_reviews_review(review: nil)
# File.write("local/gets/get_reviews_review.json", get_reviews_review.to_json)
# get_setup_attempts = api.get_setup_attempts(setup_intent: nil, ending_before: nil, expand: nil, limit: nil, starting_after: nil)
# File.write("local/gets/get_setup_attempts.json", get_setup_attempts.to_json)
get_setup_intents = api.get_setup_intents(created: nil, customer: nil, ending_before: nil, expand: nil, limit: nil, payment_method: nil, starting_after: nil)
File.write("local/gets/get_setup_intents.json", get_setup_intents.to_json)
# get_setup_intents_intent = api.get_setup_intents_intent(intent: nil, expand: nil)
# File.write("local/gets/get_setup_intents_intent.json", get_setup_intents_intent.to_json)
get_shipping_rates = api.get_shipping_rates(active: nil, created: nil, currency: nil, ending_before: nil, expand: nil, limit: nil, starting_after: nil)
File.write("local/gets/get_shipping_rates.json", get_shipping_rates.to_json)
# get_shipping_rates_shipping_rate_token = api.get_shipping_rates_shipping_rate_token(shipping_rate_token: nil)
# File.write("local/gets/get_shipping_rates_shipping_rate_token.json", get_shipping_rates_shipping_rate_token.to_json)
# get_sigma_scheduled_query_runs = api.get_sigma_scheduled_query_runs(ending_before: nil, expand: nil, limit: nil, starting_after: nil)
# File.write("local/gets/get_sigma_scheduled_query_runs.json", get_sigma_scheduled_query_runs.to_json)
# get_sigma_scheduled_query_runs_scheduled_query_run = api.get_sigma_scheduled_query_runs_scheduled_query_run(scheduled_query_run: nil)
# File.write("local/gets/get_sigma_scheduled_query_runs_scheduled_query_run.json", get_sigma_scheduled_query_runs_scheduled_query_run.to_json)
get_skus = api.get_skus(active: nil, attributes: nil, ending_before: nil, expand: nil, ids: nil, in_stock: nil, limit: nil, product: nil, starting_after: nil)
File.write("local/gets/get_skus.json", get_skus.to_json)
# get_skus_id = api.get_skus_id(id: nil)
# File.write("local/gets/get_skus_id.json", get_skus_id.to_json)
# get_sources_source = api.get_sources_source(source: nil, expand: nil)
# File.write("local/gets/get_sources_source.json", get_sources_source.to_json)
# get_sources_source_mandate_notifications_mandate_notification = api.get_sources_source_mandate_notifications_mandate_notification(mandate_notification: nil)
# File.write("local/gets/get_sources_source_mandate_notifications_mandate_notification.json", get_sources_source_mandate_notifications_mandate_notification.to_json)
# get_sources_source_source_transactions = api.get_sources_source_source_transactions(source: nil, expand: nil, limit: nil, starting_after: nil)
# File.write("local/gets/get_sources_source_source_transactions.json", get_sources_source_source_transactions.to_json)
# get_sources_source_source_transactions_source_transaction = api.get_sources_source_source_transactions_source_transaction(source: nil)
# File.write("local/gets/get_sources_source_source_transactions_source_transaction.json", get_sources_source_source_transactions_source_transaction.to_json)
# get_subscription_items = api.get_subscription_items(subscription: nil, expand: nil, limit: nil, starting_after: nil)
# File.write("local/gets/get_subscription_items.json", get_subscription_items.to_json)
# get_subscription_items_item = api.get_subscription_items_item(item: nil)
# File.write("local/gets/get_subscription_items_item.json", get_subscription_items_item.to_json)
# get_subscription_items_subscription_item_usage_record_summaries = api.get_subscription_items_subscription_item_usage_record_summaries(subscription_item: nil, expand: nil, limit: nil, starting_after: nil)
# File.write("local/gets/get_subscription_items_subscription_item_usage_record_summaries.json", get_subscription_items_subscription_item_usage_record_summaries.to_json)
get_subscription_schedules = api.get_subscription_schedules(canceled_at: nil, completed_at: nil, created: nil, customer: nil, ending_before: nil, expand: nil, limit: nil, released_at: nil, scheduled: nil, starting_after: nil)
File.write("local/gets/get_subscription_schedules.json", get_subscription_schedules.to_json)
# get_subscription_schedules_schedule = api.get_subscription_schedules_schedule(schedule: nil)
# File.write("local/gets/get_subscription_schedules_schedule.json", get_subscription_schedules_schedule.to_json)
get_subscriptions = api.get_subscriptions(collection_method: nil, created: nil, current_period_end: nil, current_period_start: nil, customer: nil, ending_before: nil, expand: nil, limit: nil, price: nil, starting_after: nil, status: nil, test_clock: nil)
File.write("local/gets/get_subscriptions.json", get_subscriptions.to_json)
# get_subscriptions_search = api.get_subscriptions_search(query: nil, limit: nil, page: nil)
# File.write("local/gets/get_subscriptions_search.json", get_subscriptions_search.to_json)
# get_subscriptions_subscription_exposed_id = api.get_subscriptions_subscription_exposed_id(subscription_exposed_id: nil)
# File.write("local/gets/get_subscriptions_subscription_exposed_id.json", get_subscriptions_subscription_exposed_id.to_json)
get_tax_codes = api.get_tax_codes(ending_before: nil, expand: nil, limit: nil, starting_after: nil)
File.write("local/gets/get_tax_codes.json", get_tax_codes.to_json)
# get_tax_codes_id = api.get_tax_codes_id(id: nil)
# File.write("local/gets/get_tax_codes_id.json", get_tax_codes_id.to_json)
get_tax_rates = api.get_tax_rates(active: nil, created: nil, ending_before: nil, expand: nil, inclusive: nil, limit: nil, starting_after: nil)
File.write("local/gets/get_tax_rates.json", get_tax_rates.to_json)
# get_tax_rates_tax_rate = api.get_tax_rates_tax_rate(tax_rate: nil)
# File.write("local/gets/get_tax_rates_tax_rate.json", get_tax_rates_tax_rate.to_json)
get_terminal_configurations = api.get_terminal_configurations(ending_before: nil, expand: nil, is_account_default: nil, limit: nil, starting_after: nil)
File.write("local/gets/get_terminal_configurations.json", get_terminal_configurations.to_json)
# get_terminal_configurations_configuration = api.get_terminal_configurations_configuration(configuration: nil)
# File.write("local/gets/get_terminal_configurations_configuration.json", get_terminal_configurations_configuration.to_json)
get_terminal_locations = api.get_terminal_locations(ending_before: nil, expand: nil, limit: nil, starting_after: nil)
File.write("local/gets/get_terminal_locations.json", get_terminal_locations.to_json)
# get_terminal_locations_location = api.get_terminal_locations_location(location: nil)
# File.write("local/gets/get_terminal_locations_location.json", get_terminal_locations_location.to_json)
get_terminal_readers = api.get_terminal_readers(device_type: nil, ending_before: nil, expand: nil, limit: nil, location: nil, starting_after: nil, status: nil)
File.write("local/gets/get_terminal_readers.json", get_terminal_readers.to_json)
# get_terminal_readers_reader = api.get_terminal_readers_reader(reader: nil)
# File.write("local/gets/get_terminal_readers_reader.json", get_terminal_readers_reader.to_json)
# get_test_helpers_test_clocks = api.get_test_helpers_test_clocks(ending_before: nil, expand: nil, limit: nil, starting_after: nil)
# File.write("local/gets/get_test_helpers_test_clocks.json", get_test_helpers_test_clocks.to_json)
# get_test_helpers_test_clocks_test_clock = api.get_test_helpers_test_clocks_test_clock(test_clock: nil)
# File.write("local/gets/get_test_helpers_test_clocks_test_clock.json", get_test_helpers_test_clocks_test_clock.to_json)
# get_tokens_token = api.get_tokens_token(token: nil)
# File.write("local/gets/get_tokens_token.json", get_tokens_token.to_json)
get_topups = api.get_topups(amount: nil, created: nil, ending_before: nil, expand: nil, limit: nil, starting_after: nil, status: nil)
File.write("local/gets/get_topups.json", get_topups.to_json)
# get_topups_topup = api.get_topups_topup(topup: nil)
# File.write("local/gets/get_topups_topup.json", get_topups_topup.to_json)
get_transfers = api.get_transfers(created: nil, destination: nil, ending_before: nil, expand: nil, limit: nil, starting_after: nil, transfer_group: nil)
File.write("local/gets/get_transfers.json", get_transfers.to_json)
# get_transfers_id_reversals = api.get_transfers_id_reversals(id: nil, expand: nil, limit: nil, starting_after: nil)
# File.write("local/gets/get_transfers_id_reversals.json", get_transfers_id_reversals.to_json)
# get_transfers_transfer = api.get_transfers_transfer(transfer: nil)
# File.write("local/gets/get_transfers_transfer.json", get_transfers_transfer.to_json)
# get_transfers_transfer_reversals_id = api.get_transfers_transfer_reversals_id(id: nil)
# File.write("local/gets/get_transfers_transfer_reversals_id.json", get_transfers_transfer_reversals_id.to_json)
# get_treasury_credit_reversals = api.get_treasury_credit_reversals(financial_account: nil, expand: nil, limit: nil, received_credit: nil, starting_after: nil, status: nil)
# File.write("local/gets/get_treasury_credit_reversals.json", get_treasury_credit_reversals.to_json)
# get_treasury_credit_reversals_credit_reversal = api.get_treasury_credit_reversals_credit_reversal(credit_reversal: nil)
# File.write("local/gets/get_treasury_credit_reversals_credit_reversal.json", get_treasury_credit_reversals_credit_reversal.to_json)
# get_treasury_debit_reversals = api.get_treasury_debit_reversals(financial_account: nil, expand: nil, limit: nil, received_debit: nil, resolution: nil, starting_after: nil, status: nil)
# File.write("local/gets/get_treasury_debit_reversals.json", get_treasury_debit_reversals.to_json)
# get_treasury_debit_reversals_debit_reversal = api.get_treasury_debit_reversals_debit_reversal(debit_reversal: nil)
# File.write("local/gets/get_treasury_debit_reversals_debit_reversal.json", get_treasury_debit_reversals_debit_reversal.to_json)
# get_treasury_financial_accounts = api.get_treasury_financial_accounts(created: nil, ending_before: nil, expand: nil, limit: nil, starting_after: nil)
# File.write("local/gets/get_treasury_financial_accounts.json", get_treasury_financial_accounts.to_json)
# get_treasury_financial_accounts_financial_account = api.get_treasury_financial_accounts_financial_account(financial_account: nil)
# File.write("local/gets/get_treasury_financial_accounts_financial_account.json", get_treasury_financial_accounts_financial_account.to_json)
# get_treasury_financial_accounts_financial_account_features = api.get_treasury_financial_accounts_financial_account_features(financial_account: nil)
# File.write("local/gets/get_treasury_financial_accounts_financial_account_features.json", get_treasury_financial_accounts_financial_account_features.to_json)
# get_treasury_inbound_transfers = api.get_treasury_inbound_transfers(financial_account: nil, expand: nil, limit: nil, starting_after: nil, status: nil)
# File.write("local/gets/get_treasury_inbound_transfers.json", get_treasury_inbound_transfers.to_json)
# get_treasury_inbound_transfers_id = api.get_treasury_inbound_transfers_id(id: nil)
# File.write("local/gets/get_treasury_inbound_transfers_id.json", get_treasury_inbound_transfers_id.to_json)
# get_treasury_outbound_payments = api.get_treasury_outbound_payments(financial_account: nil, ending_before: nil, expand: nil, limit: nil, starting_after: nil, status: nil)
# File.write("local/gets/get_treasury_outbound_payments.json", get_treasury_outbound_payments.to_json)
# get_treasury_outbound_payments_id = api.get_treasury_outbound_payments_id(id: nil)
# File.write("local/gets/get_treasury_outbound_payments_id.json", get_treasury_outbound_payments_id.to_json)
# get_treasury_outbound_transfers = api.get_treasury_outbound_transfers(financial_account: nil, expand: nil, limit: nil, starting_after: nil, status: nil)
# File.write("local/gets/get_treasury_outbound_transfers.json", get_treasury_outbound_transfers.to_json)
# get_treasury_outbound_transfers_outbound_transfer = api.get_treasury_outbound_transfers_outbound_transfer(outbound_transfer: nil)
# File.write("local/gets/get_treasury_outbound_transfers_outbound_transfer.json", get_treasury_outbound_transfers_outbound_transfer.to_json)
# get_treasury_received_credits = api.get_treasury_received_credits(financial_account: nil, expand: nil, limit: nil, linked_flows: nil, starting_after: nil, status: nil)
# File.write("local/gets/get_treasury_received_credits.json", get_treasury_received_credits.to_json)
# get_treasury_received_credits_id = api.get_treasury_received_credits_id(id: nil)
# File.write("local/gets/get_treasury_received_credits_id.json", get_treasury_received_credits_id.to_json)
# get_treasury_received_debits = api.get_treasury_received_debits(financial_account: nil, expand: nil, limit: nil, starting_after: nil, status: nil)
# File.write("local/gets/get_treasury_received_debits.json", get_treasury_received_debits.to_json)
# get_treasury_received_debits_id = api.get_treasury_received_debits_id(id: nil)
# File.write("local/gets/get_treasury_received_debits_id.json", get_treasury_received_debits_id.to_json)
# get_treasury_transaction_entries = api.get_treasury_transaction_entries(financial_account: nil, effective_at: nil, ending_before: nil, expand: nil, limit: nil, order_by: nil, starting_after: nil, transaction: nil)
# File.write("local/gets/get_treasury_transaction_entries.json", get_treasury_transaction_entries.to_json)
# get_treasury_transaction_entries_id = api.get_treasury_transaction_entries_id(id: nil)
# File.write("local/gets/get_treasury_transaction_entries_id.json", get_treasury_transaction_entries_id.to_json)
# get_treasury_transactions = api.get_treasury_transactions(financial_account: nil, ending_before: nil, expand: nil, limit: nil, order_by: nil, starting_after: nil, status: nil, status_transitions: nil)
# File.write("local/gets/get_treasury_transactions.json", get_treasury_transactions.to_json)
# get_treasury_transactions_id = api.get_treasury_transactions_id(id: nil)
# File.write("local/gets/get_treasury_transactions_id.json", get_treasury_transactions_id.to_json)
# get_webhook_endpoints = api.get_webhook_endpoints(ending_before: nil, expand: nil, limit: nil, starting_after: nil)
# File.write("local/gets/get_webhook_endpoints.json", get_webhook_endpoints.to_json)
# get_webhook_endpoints_webhook_endpoint = api.get_webhook_endpoints_webhook_endpoint(webhook_endpoint: nil)
# File.write("local/gets/get_webhook_endpoints_webhook_endpoint.json", get_webhook_endpoints_webhook_endpoint.to_json)
