#  Stripe API
#
# The Stripe REST API. Please see https://stripe.com/docs/api for more details.
#
# The version of the OpenAPI document: 2022-08-01
# Contact: dev-platform@stripe.com
# Generated by: https://openapi-generator.tech
#

require "../spec_helper"

# Unit tests for Stripe::OrdersApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe "OrdersApi" do
  describe "test an instance of OrdersApi" do
    it "should create an instance of OrdersApi" do
      api_instance = Stripe::OrdersApi.new
      api_instance.should be_a(Stripe::OrdersApi)
    end
  end

  # unit tests for get_orders
  # &lt;p&gt;Returns a list of your orders. The orders are returned sorted by creation date, with the most recently created orders appearing first.&lt;/p&gt;
  # @param [Hash] opts the optional parameters
  # @option opts [String] :ending_before A cursor for use in pagination. &#x60;ending_before&#x60; is an object ID that defines your place in the list. For instance, if you make a list request and receive 100 objects, starting with &#x60;obj_bar&#x60;, your subsequent call can include &#x60;ending_before&#x3D;obj_bar&#x60; in order to fetch the previous page of the list.
  # @option opts [String] :starting_after A cursor for use in pagination. &#x60;starting_after&#x60; is an object ID that defines your place in the list. For instance, if you make a list request and receive 100 objects, ending with &#x60;obj_foo&#x60;, your subsequent call can include &#x60;starting_after&#x3D;obj_foo&#x60; in order to fetch the next page of the list.
  # @option opts [Int32] :limit A limit on the number of objects to be returned. Limit can range between 1 and 100, and the default is 10.
  # @option opts [String] :customer Only return orders for the given customer.
  # @option opts [Array(String)] :expand Specifies which fields in the response should be expanded.
  # @return [OrdersV2ResourceOrderList]
  describe "get_orders test" do
    it "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  # unit tests for get_orders_id
  # &lt;p&gt;Retrieves the details of an existing order. Supply the unique order ID from either an order creation request or the order list, and Stripe will return the corresponding order information.&lt;/p&gt;
  # @param id
  # @param [Hash] opts the optional parameters
  # @option opts [Array(String)] :expand Specifies which fields in the response should be expanded.
  # @return [Order]
  describe "get_orders_id test" do
    it "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  # unit tests for post_orders
  # &lt;p&gt;Creates a new &lt;code&gt;open&lt;/code&gt; order object.&lt;/p&gt;
  # @param currency Three-letter [ISO currency code](https://www.iso.org/iso-4217-currency-codes.html), in lowercase. Must be a [supported currency](https://stripe.com/docs/currencies).
  # @param line_items A list of line items the customer is ordering. Each line item includes information about the product, the quantity, and the resulting cost.
  # @param [Hash] opts the optional parameters
  # @option opts [AutomaticTax] :automatic_tax
  # @option opts [PostOrdersRequestBillingDetails] :billing_details
  # @option opts [ClientPermissions] :client_permissions
  # @option opts [String] :customer The customer associated with this order.
  # @option opts [String] :description An arbitrary string attached to the object. Often useful for displaying to users.
  # @option opts [PostOrdersRequestDiscounts] :discounts
  # @option opts [Array(String)] :expand Specifies which fields in the response should be expanded.
  # @option opts [String] :ip_address The IP address of the purchaser for this order.
  # @option opts [CreateParams] :payment
  # @option opts [PostOrdersRequestShippingCost] :shipping_cost
  # @option opts [PostOrdersRequestShippingDetails] :shipping_details
  # @option opts [TaxDetails] :tax_details
  # @return [Order]
  describe "post_orders test" do
    it "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  # unit tests for post_orders_id
  # &lt;p&gt;Updates the specific order by setting the values of the parameters passed. Any parameters not provided will be left unchanged.&lt;/p&gt;
  # @param id
  # @param [Hash] opts the optional parameters
  # @option opts [AutomaticTax] :automatic_tax
  # @option opts [PostOrdersRequestBillingDetails] :billing_details
  # @option opts [ClientPermissions] :client_permissions
  # @option opts [String] :currency Three-letter [ISO currency code](https://www.iso.org/iso-4217-currency-codes.html), in lowercase. Must be a [supported currency](https://stripe.com/docs/currencies).
  # @option opts [String] :customer The customer associated with this order.
  # @option opts [String] :description An arbitrary string attached to the object. Often useful for displaying to users.
  # @option opts [PostOrdersIdRequestDiscounts] :discounts
  # @option opts [Array(String)] :expand Specifies which fields in the response should be expanded.
  # @option opts [String] :ip_address The IP address of the purchaser for this order.
  # @option opts [Array(PostOrdersIdRequestLineItemsInner)] :line_items A list of line items the customer is ordering. Each line item includes information about the product, the quantity, and the resulting cost.
  # @option opts [PostAccountsRequestMetadata] :metadata
  # @option opts [UpdateParams] :payment
  # @option opts [PostOrdersRequestShippingCost] :shipping_cost
  # @option opts [PostOrdersRequestShippingDetails] :shipping_details
  # @option opts [TaxDetails] :tax_details
  # @return [Order]
  describe "post_orders_id test" do
    it "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end
end
