#  Stripe API
#
# The Stripe REST API. Please see https://stripe.com/docs/api for more details.
#
# The version of the OpenAPI document: 2024-06-20
# Contact: dev-platform@stripe.com
# Generated by: https://openapi-generator.tech
#

# Unit tests for Stripe::BalanceAmountBySourceType
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
require "../spec_helper"
require "../../src/stripe/models/balance_amount_by_source_type"

describe Stripe::BalanceAmountBySourceType do
  describe "test an instance of BalanceAmountBySourceType" do
    it "should create an instance of BalanceAmountBySourceType" do
      # instance = Stripe::BalanceAmountBySourceType.new
      # (instance).should be_a(Stripe::BalanceAmountBySourceType)
    end
  end

  describe "test attribute 'bank_account'" do
    it "should work" do
      # instance = Stripe::BalanceAmountBySourceType.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'card'" do
    it "should work" do
      # instance = Stripe::BalanceAmountBySourceType.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'fpx'" do
    it "should work" do
      # instance = Stripe::BalanceAmountBySourceType.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end
end
