#  Stripe API
#
# The Stripe REST API. Please see https://stripe.com/docs/api for more details.
#
# The version of the OpenAPI document: 2024-06-20
# Contact: dev-platform@stripe.com
# Generated by: https://openapi-generator.tech
#

# Unit tests for Stripe::ClimateProductPricingUpdated
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
require "../spec_helper"
require "../../src/stripe/models/climate_product_pricing_updated"

describe Stripe::ClimateProductPricingUpdated do
  describe "test an instance of ClimateProductPricingUpdated" do
    it "should create an instance of ClimateProductPricingUpdated" do
      # instance = Stripe::ClimateProductPricingUpdated.new
      # (instance).should be_a(Stripe::ClimateProductPricingUpdated)
    end
  end

  describe "test attribute 'object'" do
    it "should work" do
      # instance = Stripe::ClimateProductPricingUpdated.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end
end
