#  Stripe API
#
# The Stripe REST API. Please see https://stripe.com/docs/api for more details.
#
# The version of the OpenAPI document: 2024-06-20
# Contact: dev-platform@stripe.com
# Generated by: https://openapi-generator.tech
#

# Unit tests for Stripe::ConfirmationTokensResourceShipping
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
require "../spec_helper"
require "../../src/stripe/models/confirmation_tokens_resource_shipping"

describe Stripe::ConfirmationTokensResourceShipping do
  describe "test an instance of ConfirmationTokensResourceShipping" do
    it "should create an instance of ConfirmationTokensResourceShipping" do
      # instance = Stripe::ConfirmationTokensResourceShipping.new
      # (instance).should be_a(Stripe::ConfirmationTokensResourceShipping)
    end
  end

  describe "test attribute 'address'" do
    it "should work" do
      # instance = Stripe::ConfirmationTokensResourceShipping.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'name'" do
    it "should work" do
      # instance = Stripe::ConfirmationTokensResourceShipping.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'phone'" do
    it "should work" do
      # instance = Stripe::ConfirmationTokensResourceShipping.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end
end
