#  Stripe API
#
# The Stripe REST API. Please see https://stripe.com/docs/api for more details.
#
# The version of the OpenAPI document: 2020-08-27
# Contact: dev-platform@stripe.com
# Generated by: https://openapi-generator.tech
#

require "../spec_helper"

# Unit tests for Stripe::OutboundTransfers1
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Stripe::OutboundTransfers1 do
  describe "test an instance of OutboundTransfers1" do
    it "should create an instance of OutboundTransfers1" do
      # instance = Stripe::OutboundTransfers1.new
      # expect(instance).to be_instance_of(Stripe::OutboundTransfers1)
    end
  end

  describe "test attribute 'ach'" do
    it "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'us_domestic_wire'" do
    it "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end
end
