#  Stripe API
#
# The Stripe REST API. Please see https://stripe.com/docs/api for more details.
#
# The version of the OpenAPI document: 2024-06-20
# Contact: dev-platform@stripe.com
# Generated by: https://openapi-generator.tech
#

# Unit tests for Stripe::PaymentPagesCheckoutSessionConsentCollectionPaymentMethodReuseAgreement
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
require "../spec_helper"
require "../../src/stripe/models/payment_pages_checkout_session_consent_collection_payment_method_reuse_agreement"

describe Stripe::PaymentPagesCheckoutSessionConsentCollectionPaymentMethodReuseAgreement do
end
