#  Stripe API
#
# The Stripe REST API. Please see https://stripe.com/docs/api for more details.
#
# The version of the OpenAPI document: 2022-11-15
# Contact: dev-platform@stripe.com
# Generated by: https://openapi-generator.tech
#

require "../spec_helper"

# Unit tests for Stripe::PaymentLinksResourceShippingAddressCollection
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Stripe::PaymentLinksResourceShippingAddressCollection do
  describe "test an instance of PaymentLinksResourceShippingAddressCollection" do
    it "should create an instance of PaymentLinksResourceShippingAddressCollection" do
      # instance = Stripe::PaymentLinksResourceShippingAddressCollection.new
      # (instance).should be_a(Stripe::PaymentLinksResourceShippingAddressCollection)
    end
  end

  describe "test attribute 'allowed_countries'" do
    it "should work" do
      # instance = Stripe::PaymentLinksResourceShippingAddressCollection.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
      # validator = Stripe::PaymentLinksResourceShippingAddressCollection::ENUM_VALIDATOR_FOR_ALLOWED_COUNTRIES
      # validator.allowable_values.each do |value|
      #   instance.allowed_countries = value.as(Array(String))
      # end
    end
  end
end
