#  Stripe API
#
# The Stripe REST API. Please see https://stripe.com/docs/api for more details.
#
# The version of the OpenAPI document: 2022-11-15
# Contact: dev-platform@stripe.com
# Generated by: https://openapi-generator.tech
#

require "../spec_helper"

# Unit tests for Stripe::PaymentMethodLink
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Stripe::PaymentMethodLink do
  describe "test an instance of PaymentMethodLink" do
    it "should create an instance of PaymentMethodLink" do
      # instance = Stripe::PaymentMethodLink.new
      # (instance).should be_a(Stripe::PaymentMethodLink)
    end
  end

  describe "test attribute 'email'" do
    it "should work" do
      # instance = Stripe::PaymentMethodLink.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'persistent_token'" do
    it "should work" do
      # instance = Stripe::PaymentMethodLink.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end
end
