#  Stripe API
#
# The Stripe REST API. Please see https://stripe.com/docs/api for more details.
#
# The version of the OpenAPI document: 2024-06-20
# Contact: dev-platform@stripe.com
# Generated by: https://openapi-generator.tech
#

# Unit tests for Stripe::PaymentElementParam
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
require "../spec_helper"
require "../../src/stripe/models/payment_element_param"

describe Stripe::PaymentElementParam do
  describe "test an instance of PaymentElementParam" do
    it "should create an instance of PaymentElementParam" do
      # instance = Stripe::PaymentElementParam.new
      # (instance).should be_a(Stripe::PaymentElementParam)
    end
  end

  describe "test attribute 'enabled'" do
    it "should work" do
      # instance = Stripe::PaymentElementParam.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'features'" do
    it "should work" do
      # instance = Stripe::PaymentElementParam.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end
end
