#  Stripe API
#
# The Stripe REST API. Please see https://stripe.com/docs/api for more details.
#
# The version of the OpenAPI document: 2024-06-20
# Contact: dev-platform@stripe.com
# Generated by: https://openapi-generator.tech
#

# Unit tests for Stripe::PayoutDestination
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
require "../spec_helper"
require "../../src/stripe/models/payout_destination"

describe Stripe::PayoutDestination do
  describe "test an instance of PayoutDestination" do
    it "should create an instance of PayoutDestination" do
      # instance = Stripe::PayoutDestination.new
      # (instance).should be_a(Stripe::PayoutDestination)
    end
  end

  describe "test attribute 'currency'" do
    it "should work" do
      # instance = Stripe::PayoutDestination.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'deleted'" do
    it "should work" do
      # instance = Stripe::PayoutDestination.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'id'" do
    it "should work" do
      # instance = Stripe::PayoutDestination.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'object'" do
    it "should work" do
      # instance = Stripe::PayoutDestination.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
      # validator = Stripe::PayoutDestination::ENUM_VALIDATOR_FOR_OBJECT
      # validator.allowable_values.each do |value|
      #   instance.object = value.as(String)
      # end
    end
  end

  describe "test attribute 'account'" do
    it "should work" do
      # instance = Stripe::PayoutDestination.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'account_holder_name'" do
    it "should work" do
      # instance = Stripe::PayoutDestination.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'account_holder_type'" do
    it "should work" do
      # instance = Stripe::PayoutDestination.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'account_type'" do
    it "should work" do
      # instance = Stripe::PayoutDestination.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'available_payout_methods'" do
    it "should work" do
      # instance = Stripe::PayoutDestination.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
      # validator = Stripe::PayoutDestination::ENUM_VALIDATOR_FOR_AVAILABLE_PAYOUT_METHODS
      # validator.allowable_values.each do |value|
      #   instance.available_payout_methods = value.as(Array(String))
      # end
    end
  end

  describe "test attribute 'bank_name'" do
    it "should work" do
      # instance = Stripe::PayoutDestination.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'country'" do
    it "should work" do
      # instance = Stripe::PayoutDestination.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'customer'" do
    it "should work" do
      # instance = Stripe::PayoutDestination.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'default_for_currency'" do
    it "should work" do
      # instance = Stripe::PayoutDestination.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'fingerprint'" do
    it "should work" do
      # instance = Stripe::PayoutDestination.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'future_requirements'" do
    it "should work" do
      # instance = Stripe::PayoutDestination.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'last4'" do
    it "should work" do
      # instance = Stripe::PayoutDestination.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'metadata'" do
    it "should work" do
      # instance = Stripe::PayoutDestination.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'requirements'" do
    it "should work" do
      # instance = Stripe::PayoutDestination.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'routing_number'" do
    it "should work" do
      # instance = Stripe::PayoutDestination.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'status'" do
    it "should work" do
      # instance = Stripe::PayoutDestination.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'address_city'" do
    it "should work" do
      # instance = Stripe::PayoutDestination.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'address_country'" do
    it "should work" do
      # instance = Stripe::PayoutDestination.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'address_line1'" do
    it "should work" do
      # instance = Stripe::PayoutDestination.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'address_line1_check'" do
    it "should work" do
      # instance = Stripe::PayoutDestination.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'address_line2'" do
    it "should work" do
      # instance = Stripe::PayoutDestination.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'address_state'" do
    it "should work" do
      # instance = Stripe::PayoutDestination.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'address_zip'" do
    it "should work" do
      # instance = Stripe::PayoutDestination.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'address_zip_check'" do
    it "should work" do
      # instance = Stripe::PayoutDestination.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'brand'" do
    it "should work" do
      # instance = Stripe::PayoutDestination.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'cvc_check'" do
    it "should work" do
      # instance = Stripe::PayoutDestination.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'description'" do
    it "should work" do
      # instance = Stripe::PayoutDestination.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'dynamic_last4'" do
    it "should work" do
      # instance = Stripe::PayoutDestination.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'exp_month'" do
    it "should work" do
      # instance = Stripe::PayoutDestination.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'exp_year'" do
    it "should work" do
      # instance = Stripe::PayoutDestination.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'funding'" do
    it "should work" do
      # instance = Stripe::PayoutDestination.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'iin'" do
    it "should work" do
      # instance = Stripe::PayoutDestination.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'issuer'" do
    it "should work" do
      # instance = Stripe::PayoutDestination.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'name'" do
    it "should work" do
      # instance = Stripe::PayoutDestination.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'networks'" do
    it "should work" do
      # instance = Stripe::PayoutDestination.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'tokenization_method'" do
    it "should work" do
      # instance = Stripe::PayoutDestination.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end
end
