#  Stripe API
#
# The Stripe REST API. Please see https://stripe.com/docs/api for more details.
#
# The version of the OpenAPI document: 2024-06-20
# Contact: dev-platform@stripe.com
# Generated by: https://openapi-generator.tech
#

# Unit tests for Stripe::PostPaymentMethodsPaymentMethodAttachRequest
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
require "../spec_helper"
require "../../src/stripe/models/post_payment_methods_payment_method_attach_request"

describe Stripe::PostPaymentMethodsPaymentMethodAttachRequest do
  describe "test an instance of PostPaymentMethodsPaymentMethodAttachRequest" do
    it "should create an instance of PostPaymentMethodsPaymentMethodAttachRequest" do
      # instance = Stripe::PostPaymentMethodsPaymentMethodAttachRequest.new
      # (instance).should be_a(Stripe::PostPaymentMethodsPaymentMethodAttachRequest)
    end
  end

  describe "test attribute 'customer'" do
    it "should work" do
      # instance = Stripe::PostPaymentMethodsPaymentMethodAttachRequest.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'expand'" do
    it "should work" do
      # instance = Stripe::PostPaymentMethodsPaymentMethodAttachRequest.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end
end
