#  Stripe API
#
# The Stripe REST API. Please see https://stripe.com/docs/api for more details.
#
# The version of the OpenAPI document: 2022-08-01
# Contact: dev-platform@stripe.com
# Generated by: https://openapi-generator.tech
#

require "../spec_helper"

# Unit tests for Stripe::PostCustomersCustomerTaxIdsRequest
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Stripe::PostCustomersCustomerTaxIdsRequest do
  describe "test an instance of PostCustomersCustomerTaxIdsRequest" do
    it "should create an instance of PostCustomersCustomerTaxIdsRequest" do
      # instance = Stripe::PostCustomersCustomerTaxIdsRequest.new
      # (instance).should be_a(Stripe::PostCustomersCustomerTaxIdsRequest)
    end
  end

  describe "test attribute 'expand'" do
    it "should work" do
      # instance = Stripe::PostCustomersCustomerTaxIdsRequest.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute '_type'" do
    it "should work" do
      # instance = Stripe::PostCustomersCustomerTaxIdsRequest.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
      # validator = Stripe::PostCustomersCustomerTaxIdsRequest::ENUM_VALIDATOR_FOR__TYPE
      # validator.allowable_values.each do |value|
      #   instance._type = value.as(String)
      # end
    end
  end

  describe "test attribute 'value'" do
    it "should work" do
      # instance = Stripe::PostCustomersCustomerTaxIdsRequest.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end
end
