#  Stripe API
#
# The Stripe REST API. Please see https://stripe.com/docs/api for more details.
#
# The version of the OpenAPI document: 2022-11-15
# Contact: dev-platform@stripe.com
# Generated by: https://openapi-generator.tech
#

require "../spec_helper"

# Unit tests for Stripe::PostAccountsRequest
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Stripe::PostAccountsRequest do
  describe "test an instance of PostAccountsRequest" do
    it "should create an instance of PostAccountsRequest" do
      # instance = Stripe::PostAccountsRequest.new
      # (instance).should be_a(Stripe::PostAccountsRequest)
    end
  end

  describe "test attribute 'account_token'" do
    it "should work" do
      # instance = Stripe::PostAccountsRequest.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'bank_account'" do
    it "should work" do
      # instance = Stripe::PostAccountsRequest.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'business_profile'" do
    it "should work" do
      # instance = Stripe::PostAccountsRequest.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'business_type'" do
    it "should work" do
      # instance = Stripe::PostAccountsRequest.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
      # validator = Stripe::PostAccountsRequest::ENUM_VALIDATOR_FOR_BUSINESS_TYPE
      # validator.allowable_values.each do |value|
      #   instance.business_type = value.as(String)
      # end
    end
  end

  describe "test attribute 'capabilities'" do
    it "should work" do
      # instance = Stripe::PostAccountsRequest.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'company'" do
    it "should work" do
      # instance = Stripe::PostAccountsRequest.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'country'" do
    it "should work" do
      # instance = Stripe::PostAccountsRequest.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'default_currency'" do
    it "should work" do
      # instance = Stripe::PostAccountsRequest.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'documents'" do
    it "should work" do
      # instance = Stripe::PostAccountsRequest.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'email'" do
    it "should work" do
      # instance = Stripe::PostAccountsRequest.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'expand'" do
    it "should work" do
      # instance = Stripe::PostAccountsRequest.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'external_account'" do
    it "should work" do
      # instance = Stripe::PostAccountsRequest.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'individual'" do
    it "should work" do
      # instance = Stripe::PostAccountsRequest.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'metadata'" do
    it "should work" do
      # instance = Stripe::PostAccountsRequest.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'settings'" do
    it "should work" do
      # instance = Stripe::PostAccountsRequest.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'tos_acceptance'" do
    it "should work" do
      # instance = Stripe::PostAccountsRequest.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute '_type'" do
    it "should work" do
      # instance = Stripe::PostAccountsRequest.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
      # validator = Stripe::PostAccountsRequest::ENUM_VALIDATOR_FOR__TYPE
      # validator.allowable_values.each do |value|
      #   instance._type = value.as(String)
      # end
    end
  end
end
