#  Stripe API
#
# The Stripe REST API. Please see https://stripe.com/docs/api for more details.
#
# The version of the OpenAPI document: 2024-06-20
# Contact: dev-platform@stripe.com
# Generated by: https://openapi-generator.tech
#

# Unit tests for Stripe::QuotesResourceTotalDetailsResourceBreakdown
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
require "../spec_helper"
require "../../src/stripe/models/quotes_resource_total_details_resource_breakdown"

describe Stripe::QuotesResourceTotalDetailsResourceBreakdown do
  describe "test an instance of QuotesResourceTotalDetailsResourceBreakdown" do
    it "should create an instance of QuotesResourceTotalDetailsResourceBreakdown" do
      # instance = Stripe::QuotesResourceTotalDetailsResourceBreakdown.new
      # (instance).should be_a(Stripe::QuotesResourceTotalDetailsResourceBreakdown)
    end
  end

  describe "test attribute 'discounts'" do
    it "should work" do
      # instance = Stripe::QuotesResourceTotalDetailsResourceBreakdown.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'taxes'" do
    it "should work" do
      # instance = Stripe::QuotesResourceTotalDetailsResourceBreakdown.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end
end
