#  Stripe API
#
# The Stripe REST API. Please see https://stripe.com/docs/api for more details.
#
# The version of the OpenAPI document: 2020-08-27
# Contact: dev-platform@stripe.com
# Generated by: https://openapi-generator.tech
#

require "../spec_helper"

# Unit tests for Stripe::SchedulesPhaseAutomaticTax
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Stripe::SchedulesPhaseAutomaticTax do
  describe "test an instance of SchedulesPhaseAutomaticTax" do
    it "should create an instance of SchedulesPhaseAutomaticTax" do
      # instance = Stripe::SchedulesPhaseAutomaticTax.new
      # expect(instance).to be_instance_of(Stripe::SchedulesPhaseAutomaticTax)
    end
  end

  describe "test attribute 'enabled'" do
    it "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end
end
