#  Stripe API
#
# The Stripe REST API. Please see https://stripe.com/docs/api for more details.
#
# The version of the OpenAPI document: 2020-08-27
# Contact: dev-platform@stripe.com
# Generated by: https://openapi-generator.tech
#

require "../spec_helper"

# Unit tests for Stripe::SourceMandateNotificationSepaDebitData
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Stripe::SourceMandateNotificationSepaDebitData do
  describe "test an instance of SourceMandateNotificationSepaDebitData" do
    it "should create an instance of SourceMandateNotificationSepaDebitData" do
      # instance = Stripe::SourceMandateNotificationSepaDebitData.new
      # expect(instance).to be_instance_of(Stripe::SourceMandateNotificationSepaDebitData)
    end
  end

  describe "test attribute 'creditor_identifier'" do
    it "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'last4'" do
    it "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'mandate_reference'" do
    it "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end
end
