#  Stripe API
#
# The Stripe REST API. Please see https://stripe.com/docs/api for more details.
#
# The version of the OpenAPI document: 2024-06-20
# Contact: dev-platform@stripe.com
# Generated by: https://openapi-generator.tech
#

# Unit tests for Stripe::SubscriptionDataInvoiceSettingsParams
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
require "../spec_helper"
require "../../src/stripe/models/subscription_data_invoice_settings_params"

describe Stripe::SubscriptionDataInvoiceSettingsParams do
  describe "test an instance of SubscriptionDataInvoiceSettingsParams" do
    it "should create an instance of SubscriptionDataInvoiceSettingsParams" do
      # instance = Stripe::SubscriptionDataInvoiceSettingsParams.new
      # (instance).should be_a(Stripe::SubscriptionDataInvoiceSettingsParams)
    end
  end

  describe "test attribute 'issuer'" do
    it "should work" do
      # instance = Stripe::SubscriptionDataInvoiceSettingsParams.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end
end
