#  Stripe API
#
# The Stripe REST API. Please see https://stripe.com/docs/api for more details.
#
# The version of the OpenAPI document: 2024-06-20
# Contact: dev-platform@stripe.com
# Generated by: https://openapi-generator.tech
#

# Unit tests for Stripe::SubscriptionScheduleAddInvoiceItemPrice
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
require "../spec_helper"
require "../../src/stripe/models/subscription_schedule_add_invoice_item_price"

describe Stripe::SubscriptionScheduleAddInvoiceItemPrice do
  describe "test an instance of SubscriptionScheduleAddInvoiceItemPrice" do
    it "should create an instance of SubscriptionScheduleAddInvoiceItemPrice" do
      # instance = Stripe::SubscriptionScheduleAddInvoiceItemPrice.new
      # (instance).should be_a(Stripe::SubscriptionScheduleAddInvoiceItemPrice)
    end
  end

  describe "test attribute 'deleted'" do
    it "should work" do
      # instance = Stripe::SubscriptionScheduleAddInvoiceItemPrice.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'id'" do
    it "should work" do
      # instance = Stripe::SubscriptionScheduleAddInvoiceItemPrice.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'object'" do
    it "should work" do
      # instance = Stripe::SubscriptionScheduleAddInvoiceItemPrice.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
      # validator = Stripe::SubscriptionScheduleAddInvoiceItemPrice::ENUM_VALIDATOR_FOR_OBJECT
      # validator.allowable_values.each do |value|
      #   instance.object = value.as(String)
      # end
    end
  end

  describe "test attribute 'active'" do
    it "should work" do
      # instance = Stripe::SubscriptionScheduleAddInvoiceItemPrice.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'billing_scheme'" do
    it "should work" do
      # instance = Stripe::SubscriptionScheduleAddInvoiceItemPrice.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
      # validator = Stripe::SubscriptionScheduleAddInvoiceItemPrice::ENUM_VALIDATOR_FOR_BILLING_SCHEME
      # validator.allowable_values.each do |value|
      #   instance.billing_scheme = value.as(String)
      # end
    end
  end

  describe "test attribute 'created'" do
    it "should work" do
      # instance = Stripe::SubscriptionScheduleAddInvoiceItemPrice.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'currency'" do
    it "should work" do
      # instance = Stripe::SubscriptionScheduleAddInvoiceItemPrice.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'currency_options'" do
    it "should work" do
      # instance = Stripe::SubscriptionScheduleAddInvoiceItemPrice.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'custom_unit_amount'" do
    it "should work" do
      # instance = Stripe::SubscriptionScheduleAddInvoiceItemPrice.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'livemode'" do
    it "should work" do
      # instance = Stripe::SubscriptionScheduleAddInvoiceItemPrice.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'lookup_key'" do
    it "should work" do
      # instance = Stripe::SubscriptionScheduleAddInvoiceItemPrice.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'metadata'" do
    it "should work" do
      # instance = Stripe::SubscriptionScheduleAddInvoiceItemPrice.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'nickname'" do
    it "should work" do
      # instance = Stripe::SubscriptionScheduleAddInvoiceItemPrice.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'product'" do
    it "should work" do
      # instance = Stripe::SubscriptionScheduleAddInvoiceItemPrice.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'recurring'" do
    it "should work" do
      # instance = Stripe::SubscriptionScheduleAddInvoiceItemPrice.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'tax_behavior'" do
    it "should work" do
      # instance = Stripe::SubscriptionScheduleAddInvoiceItemPrice.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
      # validator = Stripe::SubscriptionScheduleAddInvoiceItemPrice::ENUM_VALIDATOR_FOR_TAX_BEHAVIOR
      # validator.allowable_values.each do |value|
      #   instance.tax_behavior = value.as(String)
      # end
    end
  end

  describe "test attribute 'tiers'" do
    it "should work" do
      # instance = Stripe::SubscriptionScheduleAddInvoiceItemPrice.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'tiers_mode'" do
    it "should work" do
      # instance = Stripe::SubscriptionScheduleAddInvoiceItemPrice.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
      # validator = Stripe::SubscriptionScheduleAddInvoiceItemPrice::ENUM_VALIDATOR_FOR_TIERS_MODE
      # validator.allowable_values.each do |value|
      #   instance.tiers_mode = value.as(String)
      # end
    end
  end

  describe "test attribute 'transform_quantity'" do
    it "should work" do
      # instance = Stripe::SubscriptionScheduleAddInvoiceItemPrice.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute '_type'" do
    it "should work" do
      # instance = Stripe::SubscriptionScheduleAddInvoiceItemPrice.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
      # validator = Stripe::SubscriptionScheduleAddInvoiceItemPrice::ENUM_VALIDATOR_FOR__TYPE
      # validator.allowable_values.each do |value|
      #   instance._type = value.as(String)
      # end
    end
  end

  describe "test attribute 'unit_amount'" do
    it "should work" do
      # instance = Stripe::SubscriptionScheduleAddInvoiceItemPrice.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'unit_amount_decimal'" do
    it "should work" do
      # instance = Stripe::SubscriptionScheduleAddInvoiceItemPrice.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end
end
