#  Stripe API
#
# The Stripe REST API. Please see https://stripe.com/docs/api for more details.
#
# The version of the OpenAPI document: 2020-08-27
# Contact: dev-platform@stripe.com
# Generated by: https://openapi-generator.tech
#

require "../spec_helper"

# Unit tests for Stripe::SubscriptionsResourcePaymentMethodOptions
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Stripe::SubscriptionsResourcePaymentMethodOptions do
  describe "test an instance of SubscriptionsResourcePaymentMethodOptions" do
    it "should create an instance of SubscriptionsResourcePaymentMethodOptions" do
      # instance = Stripe::SubscriptionsResourcePaymentMethodOptions.new
      # expect(instance).to be_instance_of(Stripe::SubscriptionsResourcePaymentMethodOptions)
    end
  end

  describe "test attribute 'acss_debit'" do
    it "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'bancontact'" do
    it "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'card'" do
    it "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end
end
