#  Stripe API
#
# The Stripe REST API. Please see https://stripe.com/docs/api for more details.
#
# The version of the OpenAPI document: 2022-11-15
# Contact: dev-platform@stripe.com
# Generated by: https://openapi-generator.tech
#

require "../spec_helper"

# Unit tests for Stripe::SubscriptionScheduleAddInvoiceItem
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Stripe::SubscriptionScheduleAddInvoiceItem do
  describe "test an instance of SubscriptionScheduleAddInvoiceItem" do
    it "should create an instance of SubscriptionScheduleAddInvoiceItem" do
      # instance = Stripe::SubscriptionScheduleAddInvoiceItem.new
      # (instance).should be_a(Stripe::SubscriptionScheduleAddInvoiceItem)
    end
  end

  describe "test attribute 'price'" do
    it "should work" do
      # instance = Stripe::SubscriptionScheduleAddInvoiceItem.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'quantity'" do
    it "should work" do
      # instance = Stripe::SubscriptionScheduleAddInvoiceItem.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'tax_rates'" do
    it "should work" do
      # instance = Stripe::SubscriptionScheduleAddInvoiceItem.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end
end
