#  Stripe API
#
# The Stripe REST API. Please see https://stripe.com/docs/api for more details.
#
# The version of the OpenAPI document: 2022-08-01
# Contact: dev-platform@stripe.com
# Generated by: https://openapi-generator.tech
#

require "../spec_helper"

# Unit tests for Stripe::TaxParam1
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Stripe::TaxParam1 do
  describe "test an instance of TaxParam1" do
    it "should create an instance of TaxParam1" do
      # instance = Stripe::TaxParam1.new
      # (instance).should be_a(Stripe::TaxParam1)
    end
  end

  describe "test attribute 'ip_address'" do
    it "should work" do
      # instance = Stripe::TaxParam1.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end
end
