#  Stripe API
#
# The Stripe REST API. Please see https://stripe.com/docs/api for more details.
#
# The version of the OpenAPI document: 2022-11-15
# Contact: dev-platform@stripe.com
# Generated by: https://openapi-generator.tech
#

require "json"
require "time"
require "log"

module Stripe
  # ID of the corresponding charge on the platform account, if this fee was the result of a charge using the `destination` parameter.
  alias ApplicationFeeOriginatingTransaction = Charge | String
end
