#  Stripe API
#
# The Stripe REST API. Please see https://stripe.com/docs/api for more details.
#
# The version of the OpenAPI document: 2024-06-20
# Contact: dev-platform@stripe.com
# Generated by: https://openapi-generator.tech
#

require "../../core"

module Stripe
  class ControllerFeesSpecs
    include JSON::Serializable
    include JSON::Serializable::Unmapped
    include OpenApi::Validatable
    include OpenApi::Json

    # Optional Properties

    # A value indicating the responsible payer of Stripe fees on this account. Defaults to `account`. Learn more about [fee behavior on connected accounts](https://docs.stripe.com/connect/direct-charges-fee-payer-behavior).
    @[JSON::Field(key: "payer", type: String?, default: nil, required: false, nullable: false, emit_null: false)]
    getter payer : String? = nil
    ERROR_MESSAGE_FOR_PAYER = "invalid value for \"payer\", must be one of [account, application]."
    VALID_VALUES_FOR_PAYER  = String.static_array("account", "application")

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(
      *,
      # Optional properties
      @payer : String? = nil
    )
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties : Array(String)
      invalid_properties = Array(String).new

      unless (_payer = @payer).nil?
        invalid_properties.push(ERROR_MESSAGE_FOR_PAYER) unless OpenApi::EnumValidator.valid?(_payer, VALID_VALUES_FOR_PAYER)
      end
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid? : Bool
      unless (_payer = @payer).nil?
        return false unless OpenApi::EnumValidator.valid?(_payer, VALID_VALUES_FOR_PAYER)
      end

      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] payer Object to be assigned
    def payer=(new_value : String?)
      unless new_value.nil?
        OpenApi::EnumValidator.validate("payer", new_value, VALID_VALUES_FOR_PAYER)
      end

      @payer = new_value
    end

    # Generates #hash and #== methods from all fields
    # #== @return [Bool]
    # #hash calculates hash code according to all attributes.
    # #hash @return [UInt64] Hash code
    def_equals_and_hash(@payer)
  end
end
