#  Stripe API
#
# The Stripe REST API. Please see https://stripe.com/docs/api for more details.
#
# The version of the OpenAPI document: 2020-08-27
# Contact: dev-platform@stripe.com
# Generated by: https://openapi-generator.tech
#

require "json"
require "time"
require "log"

module Stripe
  # 
  @[JSON::Serializable::Options(emit_nulls: true)]
  class PaymentFlowsPrivatePaymentMethodsAlipayDetails
    include JSON::Serializable
    include JSON::Serializable::Unmapped


    # Optional properties

    # Uniquely identifies this particular Alipay account. You can use this attribute to check whether two Alipay accounts are the same.
    @[JSON::Field(key: "buyer_id", type: String?, presence: true, ignore_serialize: buyer_id.nil? && !buyer_id_present?)]
    getter buyer_id : String?

    @[JSON::Field(ignore: true)]
    property? buyer_id_present : Bool = false

    # Uniquely identifies this particular Alipay account. You can use this attribute to check whether two Alipay accounts are the same.
    @[JSON::Field(key: "fingerprint", type: String?, presence: true, ignore_serialize: fingerprint.nil? && !fingerprint_present?)]
    getter fingerprint : String?

    @[JSON::Field(ignore: true)]
    property? fingerprint_present : Bool = false

    # Transaction ID of this particular Alipay transaction.
    @[JSON::Field(key: "transaction_id", type: String?, presence: true, ignore_serialize: transaction_id.nil? && !transaction_id_present?)]
    getter transaction_id : String?

    @[JSON::Field(ignore: true)]
    property? transaction_id_present : Bool = false

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(
      *, 
      # Optional properties
      @buyer_id : String? = nil, 
      @fingerprint : String? = nil, 
      @transaction_id : String? = nil
    )
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array(String).new

      if !@buyer_id.nil? && @buyer_id.to_s.size > 5000
        invalid_properties.push("invalid value for \"buyer_id\", the character length must be smaller than or equal to 5000.")
      end

      if !@fingerprint.nil? && @fingerprint.to_s.size > 5000
        invalid_properties.push("invalid value for \"fingerprint\", the character length must be smaller than or equal to 5000.")
      end

      if !@transaction_id.nil? && @transaction_id.to_s.size > 5000
        invalid_properties.push("invalid value for \"transaction_id\", the character length must be smaller than or equal to 5000.")
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return false if !@buyer_id.nil? && @buyer_id.to_s.size > 5000
      return false if !@fingerprint.nil? && @fingerprint.to_s.size > 5000
      return false if !@transaction_id.nil? && @transaction_id.to_s.size > 5000

      true
    end

    # Custom attribute writer method with validation
    # @param [Object] buyer_id Value to be assigned
    def buyer_id=(buyer_id)
      if !buyer_id.nil? && buyer_id.to_s.size > 5000
        raise ArgumentError.new("invalid value for \"buyer_id\", the character length must be smaller than or equal to 5000.")
      end

      @buyer_id = buyer_id
    end

    # Custom attribute writer method with validation
    # @param [Object] fingerprint Value to be assigned
    def fingerprint=(fingerprint)
      if !fingerprint.nil? && fingerprint.to_s.size > 5000
        raise ArgumentError.new("invalid value for \"fingerprint\", the character length must be smaller than or equal to 5000.")
      end

      @fingerprint = fingerprint
    end

    # Custom attribute writer method with validation
    # @param [Object] transaction_id Value to be assigned
    def transaction_id=(transaction_id)
      if !transaction_id.nil? && transaction_id.to_s.size > 5000
        raise ArgumentError.new("invalid value for \"transaction_id\", the character length must be smaller than or equal to 5000.")
      end

      @transaction_id = transaction_id
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Generates #hash and #== methods from all fields
    # #== @return [Bool]
    # #hash calculates hash code according to all attributes.
    # #hash @return [UInt64] Hash code
    def_equals_and_hash(@buyer_id, @fingerprint, @transaction_id)
  end
end
