#  Stripe API
#
# The Stripe REST API. Please see https://stripe.com/docs/api for more details.
#
# The version of the OpenAPI document: 2020-08-27
# Contact: dev-platform@stripe.com
# Generated by: https://openapi-generator.tech
#

require "json"
require "time"
require "log"

module Stripe
  # The expandable object of the source flow.
  @[JSON::Serializable::Options(emit_nulls: true)]
  class ReceivedCreditsResourceTreasuryLinkedFlowsSourceFlowDetails
    include JSON::Serializable
    include JSON::Serializable::Unmapped

    # Required properties
    # The type of the source flow that originated the ReceivedCredit.
    @[JSON::Field(key: "type", type: String?)]
    getter _type : String?

    ENUM_VALIDATOR_FOR__TYPE = EnumValidator.new("_type", "String", ["credit_reversal", "other", "outbound_payment", "payout"])

    # Optional properties
    @[JSON::Field(key: "credit_reversal", type: TreasuryCreditReversal?, presence: true, ignore_serialize: credit_reversal.nil? && !credit_reversal_present?)]
    property credit_reversal : TreasuryCreditReversal?

    @[JSON::Field(ignore: true)]
    property? credit_reversal_present : Bool = false

    @[JSON::Field(key: "outbound_payment", type: TreasuryOutboundPayment?, presence: true, ignore_serialize: outbound_payment.nil? && !outbound_payment_present?)]
    property outbound_payment : TreasuryOutboundPayment?

    @[JSON::Field(ignore: true)]
    property? outbound_payment_present : Bool = false

    @[JSON::Field(key: "payout", type: Payout?, presence: true, ignore_serialize: payout.nil? && !payout_present?)]
    property payout : Payout?

    @[JSON::Field(ignore: true)]
    property? payout_present : Bool = false

    # List of class defined in anyOf (OpenAPI v3)
    def self.openapi_any_of
      [
        Stripe::ReceivedCreditsResourceTreasurySourceFlowsDetails,
      ]
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(*, @_type : String, @credit_reversal : TreasuryCreditReversal? = nil, @outbound_payment : TreasuryOutboundPayment? = nil, @payout : Payout? = nil)
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array(String).new

      invalid_properties.push(ENUM_VALIDATOR_FOR__TYPE.error_message) unless ENUM_VALIDATOR_FOR__TYPE.valid?(@_type, false)

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return false unless ENUM_VALIDATOR_FOR__TYPE.valid?(@_type, false)
      _any_of_found = false
      json_string : String = self.to_json
      _any_of_found = self.class.openapi_any_of.any? do |_class|
        _any_of = begin
          _class.from_json(json_string)
        rescue
          nil
        end

        !_any_of.nil? && _any_of.not_nil!.valid?
      end

      if !_any_of_found
        return false
      end

      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] _type Object to be assigned
    def _type=(_type)
      ENUM_VALIDATOR_FOR__TYPE.valid!(_type, false)
      @_type = _type
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.same?(o)
      self.class == o.class &&
        credit_reversal == o.credit_reversal &&
        outbound_payment == o.outbound_payment &&
        payout == o.payout &&
        _type == o._type
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [UInt64] Hash code
    def_hash(@credit_reversal, @outbound_payment, @payout, @_type)
  end
end
