#  Stripe API
#
# The Stripe REST API. Please see https://stripe.com/docs/api for more details.
#
# The version of the OpenAPI document: 2024-06-20
# Contact: dev-platform@stripe.com
# Generated by: https://openapi-generator.tech
#

require "../../core"

require "./tax_product_resource_postal_address"
require "./tax_product_resource_ship_from_details"

module Stripe
  # The details of the ship from location, such as the address.
  alias TaxCalculationShipFromDetails = TaxProductResourceShipFromDetails
end
