#  Stripe API
#
# The Stripe REST API. Please see https://stripe.com/docs/api for more details.
#
# The version of the OpenAPI document: 2022-08-01
# Contact: dev-platform@stripe.com
# Generated by: https://openapi-generator.tech
#

require "json"
require "time"
require "log"

module Stripe
  #
  class TreasuryReceivedDebitsResourceLinkedFlows
    include JSON::Serializable
    include JSON::Serializable::Unmapped
    include OpenApi::Json

    # Optional properties

    # The DebitReversal created as a result of this ReceivedDebit being reversed.
    @[JSON::Field(key: "debit_reversal", type: String?, default: nil, required: false, nullable: true, emit_null: true, presence: true, ignore_serialize: debit_reversal.nil? && !debit_reversal_present?)]
    getter debit_reversal : String? = nil

    @[JSON::Field(ignore: true)]
    property? debit_reversal_present : Bool = false

    # Set if the ReceivedDebit is associated with an InboundTransfer's return of funds.
    @[JSON::Field(key: "inbound_transfer", type: String?, default: nil, required: false, nullable: true, emit_null: true, presence: true, ignore_serialize: inbound_transfer.nil? && !inbound_transfer_present?)]
    getter inbound_transfer : String? = nil

    @[JSON::Field(ignore: true)]
    property? inbound_transfer_present : Bool = false

    # Set if the ReceivedDebit was created due to an [Issuing Authorization](https://stripe.com/docs/api#issuing_authorizations) object.
    @[JSON::Field(key: "issuing_authorization", type: String?, default: nil, required: false, nullable: true, emit_null: true, presence: true, ignore_serialize: issuing_authorization.nil? && !issuing_authorization_present?)]
    getter issuing_authorization : String? = nil

    @[JSON::Field(ignore: true)]
    property? issuing_authorization_present : Bool = false

    # Set if the ReceivedDebit is also viewable as an [Issuing Dispute](https://stripe.com/docs/api#issuing_disputes) object.
    @[JSON::Field(key: "issuing_transaction", type: String?, default: nil, required: false, nullable: true, emit_null: true, presence: true, ignore_serialize: issuing_transaction.nil? && !issuing_transaction_present?)]
    getter issuing_transaction : String? = nil

    @[JSON::Field(ignore: true)]
    property? issuing_transaction_present : Bool = false

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(
      *,
      # Optional properties
      @debit_reversal : String? = nil,
      @inbound_transfer : String? = nil,
      @issuing_authorization : String? = nil,
      @issuing_transaction : String? = nil
    )
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array(String).new
      if _debit_reversal = @debit_reversal
        if _debit_reversal.to_s.size > 5000
          invalid_properties.push("invalid value for \"debit_reversal\", the character length must be smaller than or equal to 5000.")
        end
      end
      if _inbound_transfer = @inbound_transfer
        if _inbound_transfer.to_s.size > 5000
          invalid_properties.push("invalid value for \"inbound_transfer\", the character length must be smaller than or equal to 5000.")
        end
      end
      if _issuing_authorization = @issuing_authorization
        if _issuing_authorization.to_s.size > 5000
          invalid_properties.push("invalid value for \"issuing_authorization\", the character length must be smaller than or equal to 5000.")
        end
      end
      if _issuing_transaction = @issuing_transaction
        if _issuing_transaction.to_s.size > 5000
          invalid_properties.push("invalid value for \"issuing_transaction\", the character length must be smaller than or equal to 5000.")
        end
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      if _debit_reversal = @debit_reversal
        return false if _debit_reversal.to_s.size > 5000
      end
      if _inbound_transfer = @inbound_transfer
        return false if _inbound_transfer.to_s.size > 5000
      end
      if _issuing_authorization = @issuing_authorization
        return false if _issuing_authorization.to_s.size > 5000
      end
      if _issuing_transaction = @issuing_transaction
        return false if _issuing_transaction.to_s.size > 5000
      end

      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] debit_reversal Object to be assigned
    def debit_reversal=(debit_reversal : String?)
      if debit_reversal.nil?
        return @debit_reversal = nil
      end
      _debit_reversal = debit_reversal.not_nil!
      if _debit_reversal.to_s.size > 5000
        raise ArgumentError.new("invalid value for \"debit_reversal\", the character length must be smaller than or equal to 5000.")
      end

      @debit_reversal = debit_reversal
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] inbound_transfer Object to be assigned
    def inbound_transfer=(inbound_transfer : String?)
      if inbound_transfer.nil?
        return @inbound_transfer = nil
      end
      _inbound_transfer = inbound_transfer.not_nil!
      if _inbound_transfer.to_s.size > 5000
        raise ArgumentError.new("invalid value for \"inbound_transfer\", the character length must be smaller than or equal to 5000.")
      end

      @inbound_transfer = inbound_transfer
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] issuing_authorization Object to be assigned
    def issuing_authorization=(issuing_authorization : String?)
      if issuing_authorization.nil?
        return @issuing_authorization = nil
      end
      _issuing_authorization = issuing_authorization.not_nil!
      if _issuing_authorization.to_s.size > 5000
        raise ArgumentError.new("invalid value for \"issuing_authorization\", the character length must be smaller than or equal to 5000.")
      end

      @issuing_authorization = issuing_authorization
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] issuing_transaction Object to be assigned
    def issuing_transaction=(issuing_transaction : String?)
      if issuing_transaction.nil?
        return @issuing_transaction = nil
      end
      _issuing_transaction = issuing_transaction.not_nil!
      if _issuing_transaction.to_s.size > 5000
        raise ArgumentError.new("invalid value for \"issuing_transaction\", the character length must be smaller than or equal to 5000.")
      end

      @issuing_transaction = issuing_transaction
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Generates #hash and #== methods from all fields
    # #== @return [Bool]
    # #hash calculates hash code according to all attributes.
    # #hash @return [UInt64] Hash code
    def_equals_and_hash(@debit_reversal, @debit_reversal_present, @inbound_transfer, @inbound_transfer_present, @issuing_authorization, @issuing_authorization_present, @issuing_transaction, @issuing_transaction_present)
  end
end
